import schemaJson from './insightsSchema.generated.json';

// Generated by `make insights-schema` (cmd/gen-insights-schema), which
// dumps pkg/duckdb/insights' own table/column/function registry -- the
// same source of truth validate/buildColumnHints/remapTables use -- so this
// file's shape and cmd/gen-insights-schema/main.go's JSON tags must be kept
// in sync by hand; nothing here is type-checked against the Go source.

export type InsightsSchemaColumnHint =
  | 'APP_ID'
  | 'FUNCTION_ID'
  | 'RUN_ID'
  | 'EVENT_ID';

export type InsightsSchemaColumn = {
  name: string;
  type: string;
  hint?: InsightsSchemaColumnHint;
  description: string;
};

export type InsightsSchemaTable = {
  name: string;
  description: string;
  columns: InsightsSchemaColumn[];
};

export type InsightsSchemaFunction = {
  name: string;
  description: string;
  docsUrl: string;
};

type InsightsSchema = {
  tables: InsightsSchemaTable[];
  functions: InsightsSchemaFunction[];
};

// The JSON import has no static type of its own (just inferred literal
// types), so this cast is where the file's actual shape and the types
// above are asserted to match -- there's no runtime validation.
const schema = schemaJson as InsightsSchema;

export const INSIGHTS_TABLES: readonly InsightsSchemaTable[] = schema.tables;
export const INSIGHTS_FUNCTIONS: readonly InsightsSchemaFunction[] =
  schema.functions;
