package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCollectAnnotatedTypes(t *testing.T) {
	tests := []struct {
		name      string
		files     map[string]string // filename -> content
		wantNames []string
		wantErr   string
	}{
		{
			name: "single type with annotation",
			files: map[string]string{
				"types.go": `package test

//tygo:generate
type MyStruct struct {
	Field string
}
`,
			},
			wantNames: []string{"MyStruct"},
		},
		{
			name: "const block with annotation",
			files: map[string]string{
				"consts.go": `package test

//tygo:generate
const (
	MyConst = "value"
)
`,
			},
			wantNames: []string{"MyConst"},
		},
		{
			name: "type without annotation excluded",
			files: map[string]string{
				"types.go": `package test

type NoAnnotation struct {
	Field string
}

//tygo:generate
type WithAnnotation struct {
	Field string
}
`,
			},
			wantNames: []string{"WithAnnotation"},
		},
		{
			name: "annotation with blank line still detected",
			files: map[string]string{
				"types.go": `package test

//tygo:generate

type MyStruct struct {
	Field string
}
`,
			},
			wantNames: []string{"MyStruct"},
		},
		{
			name: "multiple types in same file",
			files: map[string]string{
				"types.go": `package test

//tygo:generate
type First struct {}

//tygo:generate
type Second struct {}

type Third struct {} // no annotation
`,
			},
			wantNames: []string{"First", "Second"},
		},
		{
			name: "annotation blocked by other comment",
			files: map[string]string{
				"types.go": `package test

//tygo:generate
// This is a doc comment
type MyStruct struct {}
`,
			},
			wantNames: []string{}, // Should not be collected because doc comment is between annotation and type
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Create temp directory with test files
			tmpDir := t.TempDir()
			for filename, content := range tt.files {
				path := filepath.Join(tmpDir, filename)
				if err := os.WriteFile(path, []byte(content), 0644); err != nil {
					t.Fatalf("failed to write test file: %v", err)
				}
			}

			collected, err := collectAnnotatedTypes([]string{tmpDir})

			if tt.wantErr != "" {
				if err == nil {
					t.Fatalf("expected error containing %q, got nil", tt.wantErr)
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("expected error containing %q, got %q", tt.wantErr, err.Error())
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if len(collected) != len(tt.wantNames) {
				t.Fatalf("expected %d types, got %d", len(tt.wantNames), len(collected))
			}

			gotNames := make(map[string]bool)
			for _, c := range collected {
				gotNames[c.Name] = true
			}

			for _, want := range tt.wantNames {
				if !gotNames[want] {
					t.Errorf("expected type %q not found in collected types", want)
				}
			}
		})
	}
}

func TestDuplicateDetection(t *testing.T) {
	// Create two temp directories (simulating two packages) with same type name
	tmpDir1 := t.TempDir()
	tmpDir2 := t.TempDir()

	file1 := `package pkg1

//tygo:generate
type DuplicateName struct {}
`
	file2 := `package pkg2

//tygo:generate
type DuplicateName struct {}
`

	if err := os.WriteFile(filepath.Join(tmpDir1, "types.go"), []byte(file1), 0644); err != nil {
		t.Fatalf("failed to write test file: %v", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir2, "types.go"), []byte(file2), 0644); err != nil {
		t.Fatalf("failed to write test file: %v", err)
	}

	_, err := collectAnnotatedTypes([]string{tmpDir1, tmpDir2})
	if err == nil {
		t.Fatal("expected duplicate detection error, got nil")
	}
	if !strings.Contains(err.Error(), "duplicate type") {
		t.Fatalf("expected error about duplicate type, got: %v", err)
	}
}

func TestWriteBarrelFile(t *testing.T) {
	tmpDir := t.TempDir()
	output := filepath.Join(tmpDir, "subdir", "output.go")

	collected := []collectedType{
		{Name: "MyType", Source: "type MyType struct {}", SourceFile: "source.go"},
	}

	err := writeBarrelFile(output, "mypkg", collected)
	if err != nil {
		t.Fatalf("writeBarrelFile failed: %v", err)
	}

	content, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("failed to read output file: %v", err)
	}

	contentStr := string(content)

	// Check package name
	if !strings.Contains(contentStr, "package mypkg") {
		t.Error("output should contain correct package name")
	}

	// Check generated header
	if !strings.Contains(contentStr, "Code generated by tygo-collect") {
		t.Error("output should contain generated header")
	}

	// Check source comment
	if !strings.Contains(contentStr, "// From source.go") {
		t.Error("output should contain source file comment")
	}

	// Check type is included
	if !strings.Contains(contentStr, "type MyType struct {}") {
		t.Error("output should contain the type definition")
	}
}

func TestConstTypeAnnotationStripped(t *testing.T) {
	tmpDir := t.TempDir()

	// Create a file with a typed const
	file := `package test

//tygo:generate
const (
	MyConst SomeType = "value"
)
`
	if err := os.WriteFile(filepath.Join(tmpDir, "consts.go"), []byte(file), 0644); err != nil {
		t.Fatalf("failed to write test file: %v", err)
	}

	collected, err := collectAnnotatedTypes([]string{tmpDir})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(collected) != 1 {
		t.Fatalf("expected 1 type, got %d", len(collected))
	}

	// The type annotation should be stripped from the source
	if strings.Contains(collected[0].Source, "SomeType") {
		t.Error("const type annotation should be stripped from output")
	}
}

func TestHasAnnotation(t *testing.T) {
	tests := []struct {
		name       string
		commentMap map[int]string
		declLine   int
		want       bool
	}{
		{
			name:       "annotation immediately before",
			commentMap: map[int]string{9: "//tygo:generate"},
			declLine:   10,
			want:       true,
		},
		{
			name:       "annotation with one blank line",
			commentMap: map[int]string{8: "//tygo:generate"},
			declLine:   10,
			want:       true,
		},
		{
			name:       "annotation with two blank lines",
			commentMap: map[int]string{7: "//tygo:generate"},
			declLine:   10,
			want:       true,
		},
		{
			name:       "annotation too far away",
			commentMap: map[int]string{6: "//tygo:generate"},
			declLine:   10,
			want:       false,
		},
		{
			name:       "different comment blocks annotation",
			commentMap: map[int]string{8: "//tygo:generate", 9: "// doc comment"},
			declLine:   10,
			want:       false,
		},
		{
			name:       "no annotation",
			commentMap: map[int]string{9: "// just a comment"},
			declLine:   10,
			want:       false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := hasAnnotation(tt.commentMap, tt.declLine)
			if got != tt.want {
				t.Errorf("hasAnnotation() = %v, want %v", got, tt.want)
			}
		})
	}
}
