builds:
  -
    builder: prebuilt
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    goamd64: [v1]
    prebuilt:
      path: ./build/inngest-{{ .Os }}-{{ .Arch }}
    binary: inngest


dockers:
  - id: inngest-amd64
    goos: linux
    goarch: amd64
    skip_push: false
    use: buildx
    dockerfile: 'Dockerfile.goreleaser'
    image_templates:
    - "inngest/inngest:latest-amd64"
    - "inngest/inngest:{{ .Tag }}-amd64"
    build_flag_templates:
    - "--pull"
    - "--build-arg=BIN=inngest-linux-amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/amd64"
  - id: inngest-arm64
    goos: linux
    goarch: arm64
    skip_push: false
    use: buildx
    dockerfile: 'Dockerfile.goreleaser'
    image_templates:
    - "inngest/inngest:latest-arm64v8"
    - "inngest/inngest:{{ .Tag }}-arm64v8"
    build_flag_templates:
    - "--pull"
    - "--build-arg=BIN=inngest-linux-arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"
docker_manifests:
  - name_template: inngest/inngest:latest
    image_templates:
      - inngest/inngest:latest-amd64
      - inngest/inngest:latest-arm64v8
  - name_template: inngest/inngest:{{ .Tag }}
    image_templates:
      - inngest/inngest:{{ .Tag }}-amd64
      - inngest/inngest:{{ .Tag }}-arm64v8

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: inngest
    name: inngest
