FROM --platform=$TARGETPLATFORM debian:stable-slim@sha256:e2af2b77f6cc577b9cde8f2d0fc75584b208169453681a98440548d72a2bbcfe AS inngest
RUN apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates tzdata curl && update-ca-certificates
RUN groupadd -g 1000 inngest && useradd -u 1000 -g inngest -s /usr/sbin/nologin -M inngest
COPY inngest /bin/inngest
USER inngest
CMD ["inngest"]
