FROM --platform=$BUILDPLATFORM debian:stable-slim@sha256:e51bfcd2226c480a5416730e0fa2c40df28b0da5ff562fc465202feeef2f1116 AS inngest
RUN apt-get update && apt-get install -y ca-certificates tzdata curl && update-ca-certificates
COPY inngest /bin/inngest
CMD ["inngest"]
