// Code generated by "enumer -trimprefix=BacklogRefillConstraintCheckReason -type=BacklogRefillConstraintCheckReason -transform=snake -json -text"; DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BacklogRefillConstraintCheckReasonName = "constraint_api_uninitializedid_nilfeature_flag_disabledconstraint_api_error"

var _BacklogRefillConstraintCheckReasonIndex = [...]uint8{0, 28, 34, 55, 75}

const _BacklogRefillConstraintCheckReasonLowerName = "constraint_api_uninitializedid_nilfeature_flag_disabledconstraint_api_error"

func (i BacklogRefillConstraintCheckReason) String() string {
	if i < 0 || i >= BacklogRefillConstraintCheckReason(len(_BacklogRefillConstraintCheckReasonIndex)-1) {
		return fmt.Sprintf("BacklogRefillConstraintCheckReason(%d)", i)
	}
	return _BacklogRefillConstraintCheckReasonName[_BacklogRefillConstraintCheckReasonIndex[i]:_BacklogRefillConstraintCheckReasonIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BacklogRefillConstraintCheckReasonNoOp() {
	var x [1]struct{}
	_ = x[BacklogRefillConstraintCheckReasonConstraintAPIUninitialized-(0)]
	_ = x[BacklogRefillConstraintCheckReasonIDNil-(1)]
	_ = x[BacklogRefillConstraintCheckReasonFeatureFlagDisabled-(2)]
	_ = x[BacklogRefillConstraintCheckReasonConstraintAPIError-(3)]
}

var _BacklogRefillConstraintCheckReasonValues = []BacklogRefillConstraintCheckReason{BacklogRefillConstraintCheckReasonConstraintAPIUninitialized, BacklogRefillConstraintCheckReasonIDNil, BacklogRefillConstraintCheckReasonFeatureFlagDisabled, BacklogRefillConstraintCheckReasonConstraintAPIError}

var _BacklogRefillConstraintCheckReasonNameToValueMap = map[string]BacklogRefillConstraintCheckReason{
	_BacklogRefillConstraintCheckReasonName[0:28]:       BacklogRefillConstraintCheckReasonConstraintAPIUninitialized,
	_BacklogRefillConstraintCheckReasonLowerName[0:28]:  BacklogRefillConstraintCheckReasonConstraintAPIUninitialized,
	_BacklogRefillConstraintCheckReasonName[28:34]:      BacklogRefillConstraintCheckReasonIDNil,
	_BacklogRefillConstraintCheckReasonLowerName[28:34]: BacklogRefillConstraintCheckReasonIDNil,
	_BacklogRefillConstraintCheckReasonName[34:55]:      BacklogRefillConstraintCheckReasonFeatureFlagDisabled,
	_BacklogRefillConstraintCheckReasonLowerName[34:55]: BacklogRefillConstraintCheckReasonFeatureFlagDisabled,
	_BacklogRefillConstraintCheckReasonName[55:75]:      BacklogRefillConstraintCheckReasonConstraintAPIError,
	_BacklogRefillConstraintCheckReasonLowerName[55:75]: BacklogRefillConstraintCheckReasonConstraintAPIError,
}

var _BacklogRefillConstraintCheckReasonNames = []string{
	_BacklogRefillConstraintCheckReasonName[0:28],
	_BacklogRefillConstraintCheckReasonName[28:34],
	_BacklogRefillConstraintCheckReasonName[34:55],
	_BacklogRefillConstraintCheckReasonName[55:75],
}

// BacklogRefillConstraintCheckReasonString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BacklogRefillConstraintCheckReasonString(s string) (BacklogRefillConstraintCheckReason, error) {
	if val, ok := _BacklogRefillConstraintCheckReasonNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BacklogRefillConstraintCheckReasonNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BacklogRefillConstraintCheckReason values", s)
}

// BacklogRefillConstraintCheckReasonValues returns all values of the enum
func BacklogRefillConstraintCheckReasonValues() []BacklogRefillConstraintCheckReason {
	return _BacklogRefillConstraintCheckReasonValues
}

// BacklogRefillConstraintCheckReasonStrings returns a slice of all String values of the enum
func BacklogRefillConstraintCheckReasonStrings() []string {
	strs := make([]string, len(_BacklogRefillConstraintCheckReasonNames))
	copy(strs, _BacklogRefillConstraintCheckReasonNames)
	return strs
}

// IsABacklogRefillConstraintCheckReason returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BacklogRefillConstraintCheckReason) IsABacklogRefillConstraintCheckReason() bool {
	for _, v := range _BacklogRefillConstraintCheckReasonValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BacklogRefillConstraintCheckReason
func (i BacklogRefillConstraintCheckReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BacklogRefillConstraintCheckReason
func (i *BacklogRefillConstraintCheckReason) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BacklogRefillConstraintCheckReason should be a string, got %s", data)
	}

	var err error
	*i, err = BacklogRefillConstraintCheckReasonString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for BacklogRefillConstraintCheckReason
func (i BacklogRefillConstraintCheckReason) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for BacklogRefillConstraintCheckReason
func (i *BacklogRefillConstraintCheckReason) UnmarshalText(text []byte) error {
	var err error
	*i, err = BacklogRefillConstraintCheckReasonString(string(text))
	return err
}
