// Code generated by "enumer -trimprefix=DeferStatus -type=DeferStatus -json -text -transform=snake"; DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DeferStatusName = "unknownscheduledafter_runaborted"

var _DeferStatusIndex = [...]uint8{0, 7, 16, 25, 32}

const _DeferStatusLowerName = "unknownscheduledafter_runaborted"

func (i DeferStatus) String() string {
	if i < 0 || i >= DeferStatus(len(_DeferStatusIndex)-1) {
		return fmt.Sprintf("DeferStatus(%d)", i)
	}
	return _DeferStatusName[_DeferStatusIndex[i]:_DeferStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DeferStatusNoOp() {
	var x [1]struct{}
	_ = x[DeferStatusUnknown-(0)]
	_ = x[DeferStatusScheduled-(1)]
	_ = x[DeferStatusAfterRun-(2)]
	_ = x[DeferStatusAborted-(3)]
}

var _DeferStatusValues = []DeferStatus{DeferStatusUnknown, DeferStatusScheduled, DeferStatusAfterRun, DeferStatusAborted}

var _DeferStatusNameToValueMap = map[string]DeferStatus{
	_DeferStatusName[0:7]:        DeferStatusUnknown,
	_DeferStatusLowerName[0:7]:   DeferStatusUnknown,
	_DeferStatusName[7:16]:       DeferStatusScheduled,
	_DeferStatusLowerName[7:16]:  DeferStatusScheduled,
	_DeferStatusName[16:25]:      DeferStatusAfterRun,
	_DeferStatusLowerName[16:25]: DeferStatusAfterRun,
	_DeferStatusName[25:32]:      DeferStatusAborted,
	_DeferStatusLowerName[25:32]: DeferStatusAborted,
}

var _DeferStatusNames = []string{
	_DeferStatusName[0:7],
	_DeferStatusName[7:16],
	_DeferStatusName[16:25],
	_DeferStatusName[25:32],
}

// DeferStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DeferStatusString(s string) (DeferStatus, error) {
	if val, ok := _DeferStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DeferStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DeferStatus values", s)
}

// DeferStatusValues returns all values of the enum
func DeferStatusValues() []DeferStatus {
	return _DeferStatusValues
}

// DeferStatusStrings returns a slice of all String values of the enum
func DeferStatusStrings() []string {
	strs := make([]string, len(_DeferStatusNames))
	copy(strs, _DeferStatusNames)
	return strs
}

// IsADeferStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DeferStatus) IsADeferStatus() bool {
	for _, v := range _DeferStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DeferStatus
func (i DeferStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DeferStatus
func (i *DeferStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DeferStatus should be a string, got %s", data)
	}

	var err error
	*i, err = DeferStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for DeferStatus
func (i DeferStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DeferStatus
func (i *DeferStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = DeferStatusString(string(text))
	return err
}
