// Code generated by "enumer -trimprefix=MetadataScope -type=MetadataScope -json -text -transform=snake -gqlgen"; DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"
)

const _MetadataScopeName = "unknownrunstepstep_attemptextended_trace"

var _MetadataScopeIndex = [...]uint8{0, 7, 10, 14, 26, 40}

const _MetadataScopeLowerName = "unknownrunstepstep_attemptextended_trace"

func (i MetadataScope) String() string {
	if i < 0 || i >= MetadataScope(len(_MetadataScopeIndex)-1) {
		return fmt.Sprintf("MetadataScope(%d)", i)
	}
	return _MetadataScopeName[_MetadataScopeIndex[i]:_MetadataScopeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MetadataScopeNoOp() {
	var x [1]struct{}
	_ = x[MetadataScopeUnknown-(0)]
	_ = x[MetadataScopeRun-(1)]
	_ = x[MetadataScopeStep-(2)]
	_ = x[MetadataScopeStepAttempt-(3)]
	_ = x[MetadataScopeExtendedTrace-(4)]
}

var _MetadataScopeValues = []MetadataScope{MetadataScopeUnknown, MetadataScopeRun, MetadataScopeStep, MetadataScopeStepAttempt, MetadataScopeExtendedTrace}

var _MetadataScopeNameToValueMap = map[string]MetadataScope{
	_MetadataScopeName[0:7]:        MetadataScopeUnknown,
	_MetadataScopeLowerName[0:7]:   MetadataScopeUnknown,
	_MetadataScopeName[7:10]:       MetadataScopeRun,
	_MetadataScopeLowerName[7:10]:  MetadataScopeRun,
	_MetadataScopeName[10:14]:      MetadataScopeStep,
	_MetadataScopeLowerName[10:14]: MetadataScopeStep,
	_MetadataScopeName[14:26]:      MetadataScopeStepAttempt,
	_MetadataScopeLowerName[14:26]: MetadataScopeStepAttempt,
	_MetadataScopeName[26:40]:      MetadataScopeExtendedTrace,
	_MetadataScopeLowerName[26:40]: MetadataScopeExtendedTrace,
}

var _MetadataScopeNames = []string{
	_MetadataScopeName[0:7],
	_MetadataScopeName[7:10],
	_MetadataScopeName[10:14],
	_MetadataScopeName[14:26],
	_MetadataScopeName[26:40],
}

// MetadataScopeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MetadataScopeString(s string) (MetadataScope, error) {
	if val, ok := _MetadataScopeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MetadataScopeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MetadataScope values", s)
}

// MetadataScopeValues returns all values of the enum
func MetadataScopeValues() []MetadataScope {
	return _MetadataScopeValues
}

// MetadataScopeStrings returns a slice of all String values of the enum
func MetadataScopeStrings() []string {
	strs := make([]string, len(_MetadataScopeNames))
	copy(strs, _MetadataScopeNames)
	return strs
}

// IsAMetadataScope returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MetadataScope) IsAMetadataScope() bool {
	for _, v := range _MetadataScopeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MetadataScope
func (i MetadataScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MetadataScope
func (i *MetadataScope) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MetadataScope should be a string, got %s", data)
	}

	var err error
	*i, err = MetadataScopeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for MetadataScope
func (i MetadataScope) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MetadataScope
func (i *MetadataScope) UnmarshalText(text []byte) error {
	var err error
	*i, err = MetadataScopeString(string(text))
	return err
}

// MarshalGQL implements the graphql.Marshaler interface for MetadataScope
func (i MetadataScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for MetadataScope
func (i *MetadataScope) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("MetadataScope should be a string, got %T", value)
	}

	var err error
	*i, err = MetadataScopeString(str)
	return err
}
