// Code generated by "enumer -trimprefix=SemaphoreScope -type=SemaphoreScope -json -text -gqlgen"; DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"
)

const _SemaphoreScopeName = "FnEnvAccount"

var _SemaphoreScopeIndex = [...]uint8{0, 2, 5, 12}

const _SemaphoreScopeLowerName = "fnenvaccount"

func (i SemaphoreScope) String() string {
	if i < 0 || i >= SemaphoreScope(len(_SemaphoreScopeIndex)-1) {
		return fmt.Sprintf("SemaphoreScope(%d)", i)
	}
	return _SemaphoreScopeName[_SemaphoreScopeIndex[i]:_SemaphoreScopeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SemaphoreScopeNoOp() {
	var x [1]struct{}
	_ = x[SemaphoreScopeFn-(0)]
	_ = x[SemaphoreScopeEnv-(1)]
	_ = x[SemaphoreScopeAccount-(2)]
}

var _SemaphoreScopeValues = []SemaphoreScope{SemaphoreScopeFn, SemaphoreScopeEnv, SemaphoreScopeAccount}

var _SemaphoreScopeNameToValueMap = map[string]SemaphoreScope{
	_SemaphoreScopeName[0:2]:       SemaphoreScopeFn,
	_SemaphoreScopeLowerName[0:2]:  SemaphoreScopeFn,
	_SemaphoreScopeName[2:5]:       SemaphoreScopeEnv,
	_SemaphoreScopeLowerName[2:5]:  SemaphoreScopeEnv,
	_SemaphoreScopeName[5:12]:      SemaphoreScopeAccount,
	_SemaphoreScopeLowerName[5:12]: SemaphoreScopeAccount,
}

var _SemaphoreScopeNames = []string{
	_SemaphoreScopeName[0:2],
	_SemaphoreScopeName[2:5],
	_SemaphoreScopeName[5:12],
}

// SemaphoreScopeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SemaphoreScopeString(s string) (SemaphoreScope, error) {
	if val, ok := _SemaphoreScopeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SemaphoreScopeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SemaphoreScope values", s)
}

// SemaphoreScopeValues returns all values of the enum
func SemaphoreScopeValues() []SemaphoreScope {
	return _SemaphoreScopeValues
}

// SemaphoreScopeStrings returns a slice of all String values of the enum
func SemaphoreScopeStrings() []string {
	strs := make([]string, len(_SemaphoreScopeNames))
	copy(strs, _SemaphoreScopeNames)
	return strs
}

// IsASemaphoreScope returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SemaphoreScope) IsASemaphoreScope() bool {
	for _, v := range _SemaphoreScopeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SemaphoreScope
func (i SemaphoreScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SemaphoreScope
func (i *SemaphoreScope) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SemaphoreScope should be a string, got %s", data)
	}

	var err error
	*i, err = SemaphoreScopeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for SemaphoreScope
func (i SemaphoreScope) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SemaphoreScope
func (i *SemaphoreScope) UnmarshalText(text []byte) error {
	var err error
	*i, err = SemaphoreScopeString(string(text))
	return err
}

// MarshalGQL implements the graphql.Marshaler interface for SemaphoreScope
func (i SemaphoreScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(i.String()))
}

// UnmarshalGQL implements the graphql.Unmarshaler interface for SemaphoreScope
func (i *SemaphoreScope) UnmarshalGQL(value interface{}) error {
	str, ok := value.(string)
	if !ok {
		return fmt.Errorf("SemaphoreScope should be a string, got %T", value)
	}

	var err error
	*i, err = SemaphoreScopeString(str)
	return err
}
