/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignOutRouteImport } from "./routes/sign-out";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SignInSplatRouteImport } from "./routes/sign-in.$";
import { Route as CaseTicketIdRouteImport } from "./routes/case.$ticketId";
import { Route as AuthedSupportIndexRouteImport } from "./routes/_authed/support/index";

const SignOutRoute = SignOutRouteImport.update({
  id: "/sign-out",
  path: "/sign-out",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: "/sign-in/$",
  path: "/sign-in/$",
  getParentRoute: () => rootRouteImport,
} as any);
const CaseTicketIdRoute = CaseTicketIdRouteImport.update({
  id: "/case/$ticketId",
  path: "/case/$ticketId",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedSupportIndexRoute = AuthedSupportIndexRouteImport.update({
  id: "/support/",
  path: "/support/",
  getParentRoute: () => AuthedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/sign-out": typeof SignOutRoute;
  "/case/$ticketId": typeof CaseTicketIdRoute;
  "/sign-in/$": typeof SignInSplatRoute;
  "/support": typeof AuthedSupportIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/sign-out": typeof SignOutRoute;
  "/case/$ticketId": typeof CaseTicketIdRoute;
  "/sign-in/$": typeof SignInSplatRoute;
  "/support": typeof AuthedSupportIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/sign-out": typeof SignOutRoute;
  "/case/$ticketId": typeof CaseTicketIdRoute;
  "/sign-in/$": typeof SignInSplatRoute;
  "/_authed/support/": typeof AuthedSupportIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/sign-out" | "/case/$ticketId" | "/sign-in/$" | "/support";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/sign-out" | "/case/$ticketId" | "/sign-in/$" | "/support";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/sign-out"
    | "/case/$ticketId"
    | "/sign-in/$"
    | "/_authed/support/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  SignOutRoute: typeof SignOutRoute;
  CaseTicketIdRoute: typeof CaseTicketIdRoute;
  SignInSplatRoute: typeof SignInSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-out": {
      id: "/sign-out";
      path: "/sign-out";
      fullPath: "/sign-out";
      preLoaderRoute: typeof SignOutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in/$": {
      id: "/sign-in/$";
      path: "/sign-in/$";
      fullPath: "/sign-in/$";
      preLoaderRoute: typeof SignInSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/case/$ticketId": {
      id: "/case/$ticketId";
      path: "/case/$ticketId";
      fullPath: "/case/$ticketId";
      preLoaderRoute: typeof CaseTicketIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/support/": {
      id: "/_authed/support/";
      path: "/support";
      fullPath: "/support";
      preLoaderRoute: typeof AuthedSupportIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedSupportIndexRoute: typeof AuthedSupportIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSupportIndexRoute: AuthedSupportIndexRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignOutRoute: SignOutRoute,
  CaseTicketIdRoute: CaseTicketIdRoute,
  SignInSplatRoute: SignInSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
