// Code generated by scripts/update-duckdb-version.sh. DO NOT EDIT.

package duckdb

// PinnedVersion is the DuckDB CLI build this package downloads and runs
// against. It is a specific nightly/staged build (not a tagged GA release):
// duckdb doesn't publish stable-channel installers for the version this
// driver targets, so EnsureBinary (download.go) fetches it from DuckDB's
// staging distribution server instead — see pinnedStagedCommit and
// defaultInstallBaseURL.
const PinnedVersion = "v2.1.0-alpha40775"

// pinnedStagedCommit is the (10-character, matching DuckDB's own install
// script convention) commit hash PinnedVersion was built from, required to
// address it on the staging server — a bare version string isn't enough to
// resolve a nightly build's URL. `duckdb --version` prints this hash
// alongside the version (e.g. "v2.1.0-alpha40409 (Unknown Version)
// ecf3b9fcf1").
//
// Nightly builds are not retained indefinitely; if the staging server has
// since garbage-collected this commit, run
// scripts/update-duckdb-version.sh to bump PinnedVersion,
// pinnedStagedCommit, and pinnedChecksums together to a build that's still
// available.
const pinnedStagedCommit = "3ef446f67f"

// pinnedChecksums are the SHA256 digests of each pinned-version release
// archive EnsureBinary might download, keyed by asset name. Unlike a tagged
// GA release, DuckDB's nightly/staged channel publishes no official
// checksums at all — these were computed by downloading each archive once
// at pin time and hashing it locally. That still lets EnsureBinary fail
// closed on corruption or tampering in transit after this point, the same
// trust model as vendoring a dependency and recording its hash yourself; it
// is not a third-party attestation the way a GA release's published
// checksum would be.
var pinnedChecksums = map[string]string{
	"duckdb-cli-osx-universal.tar.gz": "061f93206431d19a47f52cc176e26e54f9940147eb950398e7c83db9b71c61c0",
	"duckdb-cli-linux-amd64.tar.gz":   "15a2d407857cb1de6e76156bb516b634a4c132dd9c46baf9a7c53cb3a60c64ed",
	"duckdb-cli-linux-arm64.tar.gz":   "cdb8c46fe16559c60c09fc9d9716906bdec997033536ec6a1b2dce5d3c29095c",
	"duckdb-cli-windows-amd64.tar.gz": "b6b59aaeee14101659cdb88db69399a2025d90e4d5ddcd74ce815cef7437403b",
}
