/**
 * The code that produced each trace. Trimmed to the shape — enough to tie the
 * drawing back to something you would have written, and no more. A figure you
 * cannot map onto your own code is asking you to reverse-engineer its point.
 *
 * Kept under ~36 columns on purpose: these sit in a narrow sticky column beside
 * the figures, and a snippet that wraps stops looking like code.
 */
export const CODE={
 c0:`await step.run('a', …)\nawait step.run('b', …)`,
 c1:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.run('c', …),\n])`,
 c2:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.run('c', …),\n])\nawait step.run('d', …)`,
 c4:`await Promise.all([\n  step.run('a', …),  // 30ms\n  step.run('b', …),  // 58ms\n  step.run('c', …),  // 12ms\n])`,
 c3:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])\nawait Promise.all([\n  step.run('a1', …),\n  step.run('a2', …),\n])`,
 c6:`await step.run('a', …)\n\nawait Promise.all([\n  step.run('b', …),\n  step.run('c', …),\n])`,
 c8:`await Promise.all([\n  (async () => {\n    await step.run('a', …)\n    await step.run('a2', …)\n  })(),\n  (async () => {\n    await step.run('b', …)\n    await step.run('b2', …)\n  })(),\n])`,
 c9:`await Promise.race([\n  step.run('fast', …),\n  step.run('slow', …),\n])\nawait step.run('next', …)`,
 c10:`await step.run('a', …)\n\n// started, never awaited\nstep.run('orphan', …)\n\nawait step.run('b', …)`,
 c11:`// an SDK that reports one\n// step per response never\n// says these were planned\n// together\nawait Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])`,
 c14:`// enqueued, then waits\n// for a worker\nawait step.run('a', …)`,
 c15:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])`,
 c16:`// { concurrency: { limit: 5 } }\nawait step.run('a', …)`,
 c16b:`// { throttle:  { limit: 10 } }\n// { rateLimit: { limit: 1 } }\n// { debounce:  { period: '5s' } }\nawait Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.run('c', …),\n])`,
 c17:`// the platform's own\n// overhead around it\nawait step.run('a', …)`,
 c18:`await step.run('last step', …)\n// then the run is finalized`,
 c19:`await step.run('a', …)`,
 c20:`// every millisecond of\n// this row is named\nawait step.run('a', …)`,
 c31:`const ids =\n  await step.sendEvent('notify', [\n    { name: 'app/thing' },\n  ])`,
 c21:`await step.run('c', …)\n// the gap between them is\n// one named interval\nawait step.run('d', …)`,
 c22:`await step.run('a',\n  async () => 'ok')`,
 c23:`await step.run('doomed', async () => {\n  throw new Error('boom')\n})`,
 c24:`try {\n  await step.run('caught', async () => {\n    throw new Error('boom')\n  })\n} catch {}\n\nawait step.run('after', …)`,
 c25:`await step.run('a', async () => {\n  if (attempt < 2)\n    throw new Error('flaky')\n  return 'ok'\n})`,
 c30:`await step.run('doomed', async () => {\n  throw new Error('always')\n})`,
 c26:`await Promise.all([\n  step.run('ok-branch', …),\n  step.run('bad-branch', …),\n])\nawait step.run('after', …)`,
 c29:`await step.run('landed', …)\nawait step.run('still going', …)`,
 c27:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),   // still running\n])\n// the run was cancelled`,
 c28:`await step.waitForEvent('w', {\n  event: 'x',\n  timeout: '1h',\n})\n// still open when the run\n// was cancelled`,
 w1:`await step.run('a', …)\n\nawait step.waitForEvent('w', {\n  event: 'app/paid',\n  timeout: '1h',\n})\n\nawait step.run('b', …)`,
 w2:`await step.run('a', …)\n\nawait step.waitForEvent('w', {\n  event: 'app/paid',\n  timeout: '1h',\n})   // nothing matched\n\nawait step.run('fallback', …)`,
 w3:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.waitForEvent('c', {\n    event: 'x',\n    timeout: '1h',\n  }),\n])\nawait step.run('d', …)`,
 w4:`await step.sleep('nap', '2s')\n\nawait step.run('a', async () => {\n  throw new Error('boom')\n})`,
 t1:`await step.run('a', …)\nawait step.sleep('nap', '7d')\nawait step.run('b', …)`,
 t2:`await step.run('a', …)\nawait step.sleep('nap', '7d')\nawait step.run('b', …)`,
 t3:`await step.run('a', …)\nawait step.run('b', …)   // a day later`,
 t4:`await step.run('a', …)     // 12ms\nawait step.sleep('nap', '2s')\nawait step.run('b', …)     // 10ms`,
 s1:`await step.run('setup', …)\n\nfor (const i of items) {        // 500\n  await step.run('fetch', …)\n}\n\nawait step.run('teardown', …)`,
 s2:`await Promise.all(\n  items.map(() =>                // 12\n    step.run('worker', …)),\n)\nawait step.run('collect', …)`,
 s3:`for (const i of items) {\n  // a cluster of these threw\n  await step.run('act', …)\n}`,
 s4:`await step.run('first', …)\n\nfor (const i of items) {        // 40\n  await step.run('batch', …)\n}\n\nawait step.run('last', …)`,
 n1:`await Promise.all([\n  step.run('fetch', …),\n  step.run('fetch', …),\n])\n// coalescing after the Promise.all\n// reports one step, so it rolls\n// into that step's row\nawait step.run('save', …)`,
 n2:`await Promise.all([\n  step.run('fetch', …),\n  step.run('fetch', …),\n])\n// the SDK reports them as\n// fetch:1 and fetch:2, assigned\n// by encounter order`,
 i1:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.run('c', …),\n])\nawait step.run('d', …)`,
 i2:`await step.run('b', …)\nawait step.run('c', …)   // threw`,
 h1:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])\n// nothing reported which of these\n// caused the request for c\nawait step.run('c', …)`,
 h2:`// reported 3ms;\n// the row spans 31ms\nawait step.run('a', …)`,
 h3:`await step.run('a', …)`,
 c67:`await step.run('a', …)\n// the request reporting b\n// threw twice first\nawait step.run('b', …)`,
 c68:`await step.run('a', …)\n// the request that would report\n// the next step never succeeded,\n// so no step exists to host it\nawait step.run('b', …)`,
};
