/**
 * The code that produced each trace. Trimmed to the shape — enough to tie the
 * drawing back to something you would have written, and no more. A figure you
 * cannot map onto your own code is asking you to reverse-engineer its point.
 *
 * Kept under ~36 columns on purpose: these sit in a narrow sticky column beside
 * the figures, and a snippet that wraps stops looking like code.
 */
export const CODE={
 c0:`await step.run('a', …)\nawait step.run('b', …)`,
 c1:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.run('c', …),\n])`,
 c2:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.run('c', …),\n])\nawait step.run('d', …)`,
 c4:`await Promise.all([\n  step.run('a', …),  // 30ms\n  step.run('b', …),  // 58ms\n  step.run('c', …),  // 12ms\n])`,
 c3:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])\nawait Promise.all([\n  step.run('a1', …),\n  step.run('a2', …),\n])`,
 c5:`const items =\n  await step.run('decide', …)\n\nawait Promise.all(\n  items.map(i =>\n    step.run(\`d\${i}\`, …)),\n)`,
 c6:`await step.run('a', …)\n\nawait Promise.all([\n  step.run('b', …),\n  step.run('c', …),\n])`,
 c8:`await Promise.all([\n  (async () => {\n    await step.run('a', …)\n    await step.run('a2', …)\n  })(),\n  (async () => {\n    await step.run('b', …)\n    await step.run('b2', …)\n  })(),\n])`,
 c7:`await Promise.all([\n  (async () => {\n    await step.run('left-1', …)\n    await step.run('left-2', …)\n  })(),\n  (async () => {\n    await step.run('right-1', …)\n    await step.run('right-2', …)\n  })(),\n])`,
 c12:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])\n// reported a then b —\n// but b started first`,
 c13:`await step.waitForEvent('w', {\n  event: 'x',\n  timeout: '1h',\n})\nawait Promise.all([\n  step.run('late', …),\n  step.run('other', …),\n])`,
 c9:`await Promise.race([\n  step.run('fast', …),\n  step.run('slow', …),\n])\nawait step.run('next', …)`,
 c10:`// started, never awaited\nstep.run('orphan', …)\n\nawait step.run('next', …)`,
 c11:`// an SDK that reports one\n// step per response never\n// says these were planned\n// together\nawait Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])`,
 c14:`// enqueued, then waits\n// for a worker\nawait step.run('a', …)`,
 c15:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])`,
 c16:`inngest.createFunction(\n  {\n    id: 'f',\n    concurrency: { limit: 5 },\n  },\n  …\n)`,
 c16b:`{ throttle: {\n    limit: 10,\n    period: '1m',\n} }\n\n{ rateLimit: {\n    limit: 1,\n    period: '1h',\n} }\n\n{ debounce: { period: '5s' } }`,
 c17:`// the platform's own\n// overhead around it\nawait step.run('a', …)`,
 c18:`// after the last step\n// resolves, the run\n// is finalized`,
 c19:`await step.run('a', …)\nawait step.sleep('nap', '2s')`,
 c20:`// every millisecond of\n// this row is named\nawait step.run('a', …)`,
 c31:`const ids =\n  await step.sendEvent('emit', [\n    { name: 'app/thing' },\n  ])`,
 c21:`await step.run('a', …)\n// the gap between them\n// is one interval\nawait step.run('b', …)`,
 c22:`await step.run('a',\n  async () => 'ok')`,
 c23:`await step.run('a', async () => {\n  throw new Error('boom')\n})`,
 c24:`try {\n  await step.run('a', async () => {\n    throw new Error('boom')\n  })\n} catch {}\n\nawait step.run('b', …)`,
 c25:`await step.run('a', async () => {\n  if (attempt < 2)\n    throw new Error('flaky')\n  return 'ok'\n})`,
 c30:`await step.run('a', async () => {\n  throw new Error('always')\n})`,
 c26:`await Promise.all([\n  step.run('good', …),\n  step.run('bad-branch', …),\n])`,
 c29:`// still running\nawait step.run('a', …)`,
 c27:`// executing when the run\n// was cancelled\nawait step.run('a', …)`,
 c28:`await step.waitForEvent('w', {\n  event: 'x',\n  timeout: '1h',\n})\n// still open when the run\n// was cancelled`,
 w1:`await step.waitForEvent('w', {\n  event: 'app/paid',\n  timeout: '1h',\n})`,
 w2:`await step.waitForEvent('w', {\n  event: 'app/paid',\n  timeout: '1h',\n})\n// nothing matched; returns\n// null and the run goes on`,
 w3:`await Promise.all([\n  step.run('a', …),\n  step.waitForEvent('w', {\n    event: 'x',\n    timeout: '1h',\n  }),\n])\nawait step.run('next', …)`,
 w4:`await step.sleep('nap', '2s')\n\nawait step.run('a', async () => {\n  throw new Error('boom')\n})`,
 t1:`await step.run('a', …)\nawait step.sleep('nap', '7d')\nawait step.run('b', …)`,
 t2:`await step.run('a', …)\nawait step.sleep('nap', '7d')\nawait step.run('b', …)`,
 t3:`await step.sleep('nap', '24h')`,
 t4:`await step.run('a', …)  // 12ms\nawait step.sleep('nap', '2s')\nawait step.run('b', …)  // 10ms`,
 s1:`// 500 of them\nfor (const i of items) {\n  await step.run(\`act-\${i}\`, …)\n}`,
 s2:`// 12 wide\nawait Promise.all(\n  items.map(i =>\n    step.run(\`w\${i}\`, …)),\n)`,
 s3:`for (const i of items) {\n  // a cluster of these threw\n  await step.run(\`act-\${i}\`, …)\n}`,
 s4:`// whatever the step count,\n// about forty rows at rest`,
 n1:`await Promise.all([\n  (async () =>\n    step.run('fetch', …))(),\n  (async () =>\n    step.run('fetch', …))(),\n])`,
 n2:`await Promise.all([\n  step.run('a', …),\n  step.run('a', …),\n])\n// the SDK's :1 / :2 are\n// assigned by encounter order`,
 i1:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])`,
 i2:`// the same trace, in the\n// same order and colours`,
 h1:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n])\n// nothing reported which of\n// these caused the next one`,
 h2:`// reported 3ms;\n// the row spans 31ms\nawait step.run('a', …)`,
 h3:`await step.run('a', …)`,
 c67:`await step.run('a', …)\n// the request reporting b\n// threw twice first\nawait step.run('b', …)`,
 c68:`await step.run('a', …)\n// the request reporting b\n// never succeeded\nawait step.run('b', …)`,
};
