/**
 * The code that produced each trace. Trimmed to the shape — enough to tie the
 * drawing back to something you would have written, and no more. A figure you
 * cannot map onto your own code is asking you to reverse-engineer its point.
 */
export const CODE={
 c0:`await step.run('a', …)\nawait step.run('b', …)`,
 c1:`await Promise.all([\n  step.run('a', …),\n  step.run('b', …),\n  step.run('c', …),\n])`,
 c2:`await Promise.all([\n  step.run('a', …), step.run('b', …), step.run('c', …),\n])\nawait step.run('d', …)`,
 c4:`await Promise.all([\n  step.run('a', …),   // 30ms\n  step.run('b', …),   // 58ms\n  step.run('c', …),   // 12ms\n])`,
 c3:`await Promise.all([step.run('a', …), step.run('b', …)])\nawait Promise.all([step.run('a1', …), step.run('a2', …)])`,
 c5:`const items = await step.run('decide', …)\nawait Promise.all(\n  items.map(i => step.run(\`d\${i}\`, …)),\n)`,
 c6:`await step.run('a', …)\nawait Promise.all([step.run('b', …), step.run('c', …)])`,
 c8:`await Promise.all([\n  (async () => { await step.run('a', …); await step.run('a2', …) })(),\n  (async () => { await step.run('b', …); await step.run('b2', …) })(),\n])`,
 c7:`await Promise.all([\n  (async () => { await step.run('left-1', …); await step.run('left-2', …) })(),\n  (async () => { await step.run('right-1', …); await step.run('right-2', …) })(),\n])`,
 c12:`await Promise.all([step.run('a', …), step.run('b', …)])\n// reported a, b — but b started first, so b is drawn first`,
 c13:`await step.waitForEvent('w', { event: 'x', timeout: '1h' })\nawait Promise.all([step.run('late', …), step.run('other', …)])`,
 c9:`await Promise.race([step.run('fast', …), step.run('slow', …)])\nawait step.run('next', …)`,
 c10:`step.run('orphan', …)          // started, never awaited\nawait step.run('next', …)`,
 c11:`// same code as the fan-out above, on an SDK that reports\n// one opcode per response — so the grouping is recovered\n// from overlap rather than read off the request\nawait Promise.all([step.run('a', …), step.run('b', …)])`,
 c14:`await step.run('a', …)   // enqueued, then waits for a worker`,
 c15:`await Promise.all([step.run('a', …), step.run('b', …)])`,
 c16:`export default inngest.createFunction(\n  { id: 'f', concurrency: { limit: 5 } }, …\n)`,
 c16b:`{ throttle: { limit: 10, period: '1m' } }\n{ rateLimit: { limit: 1, period: '1h' } }\n{ debounce: { period: '5s' } }`,
 c17:`await step.run('a', …)   // the platform's own overhead around it`,
 c18:`// after the last step resolves, the run is finalized`,
 c19:`await step.run('a', …)\nawait step.sleep('nap', '2s')`,
 c20:`await step.run('a', …)   // every millisecond of this row is named`,
 c31:`const ids = await step.sendEvent('emit', [\n  { name: 'app/thing.happened' },\n])`,
 c21:`await step.run('a', …)\nawait step.run('b', …)   // the gap between them is one interval`,
 c22:`await step.run('a', async () => 'ok')`,
 c23:`await step.run('a', async () => { throw new Error('boom') })`,
 c24:`try {\n  await step.run('a', async () => { throw new Error('boom') })\n} catch {}\nawait step.run('b', …)`,
 c25:`await step.run('a', async () => {\n  if (attempt < 2) throw new Error('flaky')\n  return 'ok'\n})`,
 c30:`await step.run('a', async () => { throw new Error('always') })`,
 c26:`await Promise.all([step.run('good', …), step.run('bad-branch', …)])`,
 c29:`await step.run('a', …)   // still running`,
 c27:`await step.run('a', …)   // executing when the run was cancelled`,
 c28:`await step.waitForEvent('w', { event: 'x', timeout: '1h' })\n// still open when the run was cancelled`,
 w1:`await step.waitForEvent('w', { event: 'app/paid', timeout: '1h' })`,
 w2:`await step.waitForEvent('w', { event: 'app/paid', timeout: '1h' })\n// nothing matched; returns null and the run carries on`,
 w3:`await Promise.all([\n  step.run('a', …),\n  step.waitForEvent('w', { event: 'x', timeout: '1h' }),\n])\nawait step.run('next', …)`,
 w4:`await step.sleep('nap', '2s')\nawait step.run('a', async () => { throw new Error('boom') })`,
 t1:`await step.run('a', …)\nawait step.sleep('nap', '7d')\nawait step.run('b', …)`,
 t2:`await step.run('a', …)\nawait step.sleep('nap', '7d')\nawait step.run('b', …)`,
 t3:`await step.sleep('nap', '24h')`,
 t4:`await step.run('a', …)     // 12ms\nawait step.sleep('nap', '2s')\nawait step.run('b', …)     // 10ms`,
 s1:`for (const i of items) {        // 500 of them\n  await step.run(\`act-\${i}\`, …)\n}`,
 s2:`await Promise.all(\n  items.map(i => step.run(\`w\${i}\`, …)),   // 12 wide\n)`,
 s3:`for (const i of items) {\n  await step.run(\`act-\${i}\`, …)   // a cluster of these threw\n}`,
 s4:`// whatever the step count, about forty rows at rest`,
 n1:`await Promise.all([\n  (async () => { await step.run('fetch', …) })(),\n  (async () => { await step.run('fetch', …) })(),\n])`,
 n2:`await Promise.all([step.run('a', …), step.run('a', …)])\n// the SDK's :1 / :2 are assigned by encounter order`,
 i1:`await Promise.all([step.run('a', …), step.run('b', …)])`,
 i2:`// the same trace, in the same order and the same colours`,
 h1:`await Promise.all([step.run('a', …), step.run('b', …)])\n// nothing reported which of these caused the next request`,
 h2:`await step.run('a', …)   // reported 3ms; the row spans 31ms`,
 h3:`await step.run('a', …)`,
 c67:`await step.run('a', …)\nawait step.run('b', …)   // the request reporting b threw twice first`,
 c68:`await step.run('a', …)\nawait step.run('b', …)   // the request reporting b never succeeded`,
};
