// Code generated by protoc-gen-inngest-includes. DO NOT EDIT.

package apiv2

import (
	apiv2endpoint "github.com/inngest/inngest/pkg/api/v2/apiv2endpoint"
)

// GetEventRunsInclude is an internal expansion selected by generated API parsers.
type GetEventRunsInclude uint8

const (
	GetEventRunsIncludeOutput GetEventRunsInclude = iota + 1
)

// GetFunctionRunInclude is an internal expansion selected by generated API parsers.
type GetFunctionRunInclude uint8

const (
	GetFunctionRunIncludeOutput GetFunctionRunInclude = iota + 1
)

// GetFunctionTraceInclude is an internal expansion selected by generated API parsers.
type GetFunctionTraceInclude uint8

const (
	GetFunctionTraceIncludeOutput GetFunctionTraceInclude = iota + 1
)

// ListFunctionRunsInclude is an internal expansion selected by generated API parsers.
type ListFunctionRunsInclude uint8

const (
	ListFunctionRunsIncludeDeferredFrom ListFunctionRunsInclude = iota + 1
	ListFunctionRunsIncludeOutput
)

// ListRunsInclude is an internal expansion selected by generated API parsers.
type ListRunsInclude uint8

const (
	ListRunsIncludeDeferredFrom ListRunsInclude = iota + 1
	ListRunsIncludeOutput
)

var getEventRunsIncludeSelector = apiv2endpoint.NewIncludeSelector(map[string]GetEventRunsInclude{
	"output": GetEventRunsIncludeOutput,
})

// ParseGetEventRunsInclude parses a canonical selector or its snake_case compatibility alias.
func ParseGetEventRunsInclude(value string) (GetEventRunsInclude, error) {
	return getEventRunsIncludeSelector.Parse(value)
}

var getFunctionRunIncludeSelector = apiv2endpoint.NewIncludeSelector(map[string]GetFunctionRunInclude{
	"output": GetFunctionRunIncludeOutput,
})

// ParseGetFunctionRunInclude parses a canonical selector or its snake_case compatibility alias.
func ParseGetFunctionRunInclude(value string) (GetFunctionRunInclude, error) {
	return getFunctionRunIncludeSelector.Parse(value)
}

var getFunctionTraceIncludeSelector = apiv2endpoint.NewIncludeSelector(map[string]GetFunctionTraceInclude{
	"output": GetFunctionTraceIncludeOutput,
})

// ParseGetFunctionTraceInclude parses a canonical selector or its snake_case compatibility alias.
func ParseGetFunctionTraceInclude(value string) (GetFunctionTraceInclude, error) {
	return getFunctionTraceIncludeSelector.Parse(value)
}

var listFunctionRunsIncludeSelector = apiv2endpoint.NewIncludeSelector(map[string]ListFunctionRunsInclude{
	"deferredFrom":  ListFunctionRunsIncludeDeferredFrom,
	"deferred_from": ListFunctionRunsIncludeDeferredFrom,
	"output":        ListFunctionRunsIncludeOutput,
})

// ParseListFunctionRunsInclude parses a canonical selector or its snake_case compatibility alias.
func ParseListFunctionRunsInclude(value string) (ListFunctionRunsInclude, error) {
	return listFunctionRunsIncludeSelector.Parse(value)
}

var listRunsIncludeSelector = apiv2endpoint.NewIncludeSelector(map[string]ListRunsInclude{
	"deferredFrom":  ListRunsIncludeDeferredFrom,
	"deferred_from": ListRunsIncludeDeferredFrom,
	"output":        ListRunsIncludeOutput,
})

// ParseListRunsInclude parses a canonical selector or its snake_case compatibility alias.
func ParseListRunsInclude(value string) (ListRunsInclude, error) {
	return listRunsIncludeSelector.Parse(value)
}
