// Code generated by protoc-gen-inngest-includes. DO NOT EDIT.

package apiv2

import (
	apiv2endpoint "github.com/inngest/inngest/pkg/api/v2/apiv2endpoint"
)

const (
	RunListIncludeDeferredFrom RunListInclude = iota + 1
	RunListIncludeOutput
)

var listFunctionRunsIncludeSelector = apiv2endpoint.NewIncludeSelector(map[string]RunListInclude{
	"deferredFrom":  RunListIncludeDeferredFrom,
	"deferred_from": RunListIncludeDeferredFrom,
	"output":        RunListIncludeOutput,
})

var listRunsIncludeSelector = apiv2endpoint.NewIncludeSelector(map[string]RunListInclude{
	"deferredFrom":  RunListIncludeDeferredFrom,
	"deferred_from": RunListIncludeDeferredFrom,
	"output":        RunListIncludeOutput,
})
