/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthedOrgActiveRouteImport } from './routes/_authed/_org-active'
import { Route as AuthedOrgActiveEnvEnvSlugRouteRouteImport } from './routes/_authed/_org-active/env/$envSlug/route'
import { Route as AuthedOrgActiveEnvEnvSlugAppsRouteRouteImport } from './routes/_authed/_org-active/env/$envSlug/apps/route'
import { Route as AuthedOrgActiveEnvEnvSlugRunsIndexRouteImport } from './routes/_authed/_org-active/env/$envSlug/runs/index'
import { Route as AuthedOrgActiveEnvEnvSlugFunctionsIndexRouteImport } from './routes/_authed/_org-active/env/$envSlug/functions/index'
import { Route as AuthedOrgActiveEnvEnvSlugEventsIndexRouteImport } from './routes/_authed/_org-active/env/$envSlug/events/index'
import { Route as AuthedOrgActiveEnvEnvSlugEventTypesIndexRouteImport } from './routes/_authed/_org-active/env/$envSlug/event-types/index'
import { Route as AuthedOrgActiveEnvEnvSlugAppsIndexRouteImport } from './routes/_authed/_org-active/env/$envSlug/apps/index'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgActiveRoute = AuthedOrgActiveRouteImport.update({
  id: '/_org-active',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgActiveEnvEnvSlugRouteRoute =
  AuthedOrgActiveEnvEnvSlugRouteRouteImport.update({
    id: '/env/$envSlug',
    path: '/env/$envSlug',
    getParentRoute: () => AuthedOrgActiveRoute,
  } as any)
const AuthedOrgActiveEnvEnvSlugAppsRouteRoute =
  AuthedOrgActiveEnvEnvSlugAppsRouteRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => AuthedOrgActiveEnvEnvSlugRouteRoute,
  } as any)
const AuthedOrgActiveEnvEnvSlugRunsIndexRoute =
  AuthedOrgActiveEnvEnvSlugRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AuthedOrgActiveEnvEnvSlugRouteRoute,
  } as any)
const AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute =
  AuthedOrgActiveEnvEnvSlugFunctionsIndexRouteImport.update({
    id: '/functions/',
    path: '/functions/',
    getParentRoute: () => AuthedOrgActiveEnvEnvSlugRouteRoute,
  } as any)
const AuthedOrgActiveEnvEnvSlugEventsIndexRoute =
  AuthedOrgActiveEnvEnvSlugEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthedOrgActiveEnvEnvSlugRouteRoute,
  } as any)
const AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute =
  AuthedOrgActiveEnvEnvSlugEventTypesIndexRouteImport.update({
    id: '/event-types/',
    path: '/event-types/',
    getParentRoute: () => AuthedOrgActiveEnvEnvSlugRouteRoute,
  } as any)
const AuthedOrgActiveEnvEnvSlugAppsIndexRoute =
  AuthedOrgActiveEnvEnvSlugAppsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgActiveEnvEnvSlugAppsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-out': typeof SignOutRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/env/$envSlug': typeof AuthedOrgActiveEnvEnvSlugRouteRouteWithChildren
  '/env/$envSlug/apps': typeof AuthedOrgActiveEnvEnvSlugAppsRouteRouteWithChildren
  '/env/$envSlug/apps/': typeof AuthedOrgActiveEnvEnvSlugAppsIndexRoute
  '/env/$envSlug/event-types': typeof AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute
  '/env/$envSlug/events': typeof AuthedOrgActiveEnvEnvSlugEventsIndexRoute
  '/env/$envSlug/functions': typeof AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute
  '/env/$envSlug/runs': typeof AuthedOrgActiveEnvEnvSlugRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-out': typeof SignOutRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/env/$envSlug': typeof AuthedOrgActiveEnvEnvSlugRouteRouteWithChildren
  '/env/$envSlug/apps': typeof AuthedOrgActiveEnvEnvSlugAppsIndexRoute
  '/env/$envSlug/event-types': typeof AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute
  '/env/$envSlug/events': typeof AuthedOrgActiveEnvEnvSlugEventsIndexRoute
  '/env/$envSlug/functions': typeof AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute
  '/env/$envSlug/runs': typeof AuthedOrgActiveEnvEnvSlugRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-out': typeof SignOutRoute
  '/_authed/_org-active': typeof AuthedOrgActiveRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authed/_org-active/env/$envSlug': typeof AuthedOrgActiveEnvEnvSlugRouteRouteWithChildren
  '/_authed/_org-active/env/$envSlug/apps': typeof AuthedOrgActiveEnvEnvSlugAppsRouteRouteWithChildren
  '/_authed/_org-active/env/$envSlug/apps/': typeof AuthedOrgActiveEnvEnvSlugAppsIndexRoute
  '/_authed/_org-active/env/$envSlug/event-types/': typeof AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute
  '/_authed/_org-active/env/$envSlug/events/': typeof AuthedOrgActiveEnvEnvSlugEventsIndexRoute
  '/_authed/_org-active/env/$envSlug/functions/': typeof AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute
  '/_authed/_org-active/env/$envSlug/runs/': typeof AuthedOrgActiveEnvEnvSlugRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-out'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/env/$envSlug'
    | '/env/$envSlug/apps'
    | '/env/$envSlug/apps/'
    | '/env/$envSlug/event-types'
    | '/env/$envSlug/events'
    | '/env/$envSlug/functions'
    | '/env/$envSlug/runs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-out'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/env/$envSlug'
    | '/env/$envSlug/apps'
    | '/env/$envSlug/event-types'
    | '/env/$envSlug/events'
    | '/env/$envSlug/functions'
    | '/env/$envSlug/runs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-out'
    | '/_authed/_org-active'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authed/_org-active/env/$envSlug'
    | '/_authed/_org-active/env/$envSlug/apps'
    | '/_authed/_org-active/env/$envSlug/apps/'
    | '/_authed/_org-active/env/$envSlug/event-types/'
    | '/_authed/_org-active/env/$envSlug/events/'
    | '/_authed/_org-active/env/$envSlug/functions/'
    | '/_authed/_org-active/env/$envSlug/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignOutRoute: typeof SignOutRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_org-active': {
      id: '/_authed/_org-active'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedOrgActiveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_org-active/env/$envSlug': {
      id: '/_authed/_org-active/env/$envSlug'
      path: '/env/$envSlug'
      fullPath: '/env/$envSlug'
      preLoaderRoute: typeof AuthedOrgActiveEnvEnvSlugRouteRouteImport
      parentRoute: typeof AuthedOrgActiveRoute
    }
    '/_authed/_org-active/env/$envSlug/apps': {
      id: '/_authed/_org-active/env/$envSlug/apps'
      path: '/apps'
      fullPath: '/env/$envSlug/apps'
      preLoaderRoute: typeof AuthedOrgActiveEnvEnvSlugAppsRouteRouteImport
      parentRoute: typeof AuthedOrgActiveEnvEnvSlugRouteRoute
    }
    '/_authed/_org-active/env/$envSlug/runs/': {
      id: '/_authed/_org-active/env/$envSlug/runs/'
      path: '/runs'
      fullPath: '/env/$envSlug/runs'
      preLoaderRoute: typeof AuthedOrgActiveEnvEnvSlugRunsIndexRouteImport
      parentRoute: typeof AuthedOrgActiveEnvEnvSlugRouteRoute
    }
    '/_authed/_org-active/env/$envSlug/functions/': {
      id: '/_authed/_org-active/env/$envSlug/functions/'
      path: '/functions'
      fullPath: '/env/$envSlug/functions'
      preLoaderRoute: typeof AuthedOrgActiveEnvEnvSlugFunctionsIndexRouteImport
      parentRoute: typeof AuthedOrgActiveEnvEnvSlugRouteRoute
    }
    '/_authed/_org-active/env/$envSlug/events/': {
      id: '/_authed/_org-active/env/$envSlug/events/'
      path: '/events'
      fullPath: '/env/$envSlug/events'
      preLoaderRoute: typeof AuthedOrgActiveEnvEnvSlugEventsIndexRouteImport
      parentRoute: typeof AuthedOrgActiveEnvEnvSlugRouteRoute
    }
    '/_authed/_org-active/env/$envSlug/event-types/': {
      id: '/_authed/_org-active/env/$envSlug/event-types/'
      path: '/event-types'
      fullPath: '/env/$envSlug/event-types'
      preLoaderRoute: typeof AuthedOrgActiveEnvEnvSlugEventTypesIndexRouteImport
      parentRoute: typeof AuthedOrgActiveEnvEnvSlugRouteRoute
    }
    '/_authed/_org-active/env/$envSlug/apps/': {
      id: '/_authed/_org-active/env/$envSlug/apps/'
      path: '/'
      fullPath: '/env/$envSlug/apps/'
      preLoaderRoute: typeof AuthedOrgActiveEnvEnvSlugAppsIndexRouteImport
      parentRoute: typeof AuthedOrgActiveEnvEnvSlugAppsRouteRoute
    }
  }
}

interface AuthedOrgActiveEnvEnvSlugAppsRouteRouteChildren {
  AuthedOrgActiveEnvEnvSlugAppsIndexRoute: typeof AuthedOrgActiveEnvEnvSlugAppsIndexRoute
}

const AuthedOrgActiveEnvEnvSlugAppsRouteRouteChildren: AuthedOrgActiveEnvEnvSlugAppsRouteRouteChildren =
  {
    AuthedOrgActiveEnvEnvSlugAppsIndexRoute:
      AuthedOrgActiveEnvEnvSlugAppsIndexRoute,
  }

const AuthedOrgActiveEnvEnvSlugAppsRouteRouteWithChildren =
  AuthedOrgActiveEnvEnvSlugAppsRouteRoute._addFileChildren(
    AuthedOrgActiveEnvEnvSlugAppsRouteRouteChildren,
  )

interface AuthedOrgActiveEnvEnvSlugRouteRouteChildren {
  AuthedOrgActiveEnvEnvSlugAppsRouteRoute: typeof AuthedOrgActiveEnvEnvSlugAppsRouteRouteWithChildren
  AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute: typeof AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute
  AuthedOrgActiveEnvEnvSlugEventsIndexRoute: typeof AuthedOrgActiveEnvEnvSlugEventsIndexRoute
  AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute: typeof AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute
  AuthedOrgActiveEnvEnvSlugRunsIndexRoute: typeof AuthedOrgActiveEnvEnvSlugRunsIndexRoute
}

const AuthedOrgActiveEnvEnvSlugRouteRouteChildren: AuthedOrgActiveEnvEnvSlugRouteRouteChildren =
  {
    AuthedOrgActiveEnvEnvSlugAppsRouteRoute:
      AuthedOrgActiveEnvEnvSlugAppsRouteRouteWithChildren,
    AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute:
      AuthedOrgActiveEnvEnvSlugEventTypesIndexRoute,
    AuthedOrgActiveEnvEnvSlugEventsIndexRoute:
      AuthedOrgActiveEnvEnvSlugEventsIndexRoute,
    AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute:
      AuthedOrgActiveEnvEnvSlugFunctionsIndexRoute,
    AuthedOrgActiveEnvEnvSlugRunsIndexRoute:
      AuthedOrgActiveEnvEnvSlugRunsIndexRoute,
  }

const AuthedOrgActiveEnvEnvSlugRouteRouteWithChildren =
  AuthedOrgActiveEnvEnvSlugRouteRoute._addFileChildren(
    AuthedOrgActiveEnvEnvSlugRouteRouteChildren,
  )

interface AuthedOrgActiveRouteChildren {
  AuthedOrgActiveEnvEnvSlugRouteRoute: typeof AuthedOrgActiveEnvEnvSlugRouteRouteWithChildren
}

const AuthedOrgActiveRouteChildren: AuthedOrgActiveRouteChildren = {
  AuthedOrgActiveEnvEnvSlugRouteRoute:
    AuthedOrgActiveEnvEnvSlugRouteRouteWithChildren,
}

const AuthedOrgActiveRouteWithChildren = AuthedOrgActiveRoute._addFileChildren(
  AuthedOrgActiveRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOrgActiveRoute: typeof AuthedOrgActiveRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrgActiveRoute: AuthedOrgActiveRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignOutRoute: SignOutRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
