package meta

import (
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/inngest/inngest/pkg/enums"
	"github.com/inngest/inngest/pkg/tracing/metadata"
	"github.com/inngest/inngest/pkg/util/aigateway"
	"github.com/oklog/ulid/v2"
)

var Attrs = struct {
	// Timings
	StartedAt attr[*time.Time]
	QueuedAt  attr[*time.Time]
	EndedAt   attr[*time.Time]

	// Run attributes
	AccountID           attr[*uuid.UUID]
	AppID               attr[*uuid.UUID]
	BatchID             attr[*ulid.ULID]
	BatchTimestamp      attr[*time.Time]
	CronSchedule        attr[*string]
	DropSpan            attr[*bool]
	EnvID               attr[*uuid.UUID]
	EventIDs            attr[*[]string]
	EventsInput         attr[*string]
	TriggeringEventName attr[*string]
	FunctionID          attr[*uuid.UUID]
	FunctionVersion     attr[*int]
	RunID               attr[*ulid.ULID]

	// Durable endpoint attributes
	IsDurableEndpointRun         attr[*bool]
	DurableEndpointModeChangedAt attr[*time.Time]

	// Dynamic span controls
	DynamicSpanID attr[*string]
	DynamicStatus attr[*enums.StepStatus]
	// DynamicTraceID is a trace ID for this span that should overwrite
	// whatever trace ID is currently set within the span's own context.
	//
	// We need this due to Go's otel library sometimes being stubborn about
	// inheriting a particular `traceparent`'s context based on span IDs. In
	// our particular case, a zero-value span ID (e.g. `"0000000000000000"`)
	// would result in the entire `traceparent` being ignored and a new trace
	// ID being created.
	DynamicTraceID attr[*string]

	// Internal and debugging
	InternalLocation attr[*string]
	// Internal as we want this only to be set by internal logic.
	internalError attr[*string]

	// Function attributes
	IsFunctionOutput attr[*bool]

	// Retryable records whether the attempt is retryable.
	Retryable attr[*bool]

	// Step attributes
	StepID           attr[*string]
	StepName         attr[*string]
	StepOp           attr[*enums.Opcode]
	StepAttempt      attr[*int]
	StepMaxAttempts  attr[*int]
	StepCodeLocation attr[*string]
	// StepInput is the data that has been explicitly captured as input for a
	// step. This data may not be stored with the span when it hits a store,
	// and instead may be removed to be stored separately.
	StepInput attr[*string]
	// StepOutput is the data that has been returned from the step, in
	// its wrapped form for the SDK. This data may not be stored with the span
	// when it hits a store, and instead may be removed to be stored
	// separately.
	StepOutput    attr[*string]
	StepOutputRef attr[*string]
	// StepHasOutput is used to mark that a specific span has an output in the
	// attributes, in place of the output itself.
	StepHasOutput attr[*bool]

	// The ID of the step that was passed by the user
	StepUserlandID attr[*string]
	// The autogenerated ID from the SDK for repeated step IDs
	StepUserlandIndex attr[*int]

	// step.run attributes
	StepRunType attr[*string]

	// Pause-related attributes
	StepWaitExpired attr[*bool]
	StepWaitExpiry  attr[*time.Time]

	// Invoke attributes
	StepInvokeFunctionID     attr[*string]
	StepInvokeTriggerEventID attr[*ulid.ULID]
	StepInvokeFinishEventID  attr[*ulid.ULID]
	StepInvokeRunID          attr[*ulid.ULID]

	// step.sleep attributes
	StepSleepDuration attr[*time.Duration]

	// step.waitForEvent attributes
	StepWaitForEventIf        attr[*string]
	StepWaitForEventName      attr[*string]
	StepWaitForEventMatchedID attr[*ulid.ULID]

	// Signal attributes
	StepSignalName attr[*string]

	// Gateway attributes
	StepGatewayResponseStatusCode      attr[*int]
	StepGatewayResponseOutputSizeBytes attr[*int]

	// HTTP (serve) attributes
	RequestURL         attr[*string]
	ResponseHeaders    attr[*http.Header]
	ResponseStatusCode attr[*int]
	ResponseOutputSize attr[*int]

	IsCheckpoint attr[*bool]

	// Userland attributes
	IsUserland                 attr[*bool]
	UserlandSpanID             attr[*string]
	UserlandName               attr[*string]
	UserlandKind               attr[*string]
	UserlandServiceName        attr[*string]
	UserlandScopeName          attr[*string]
	UserlandScopeVersion       attr[*string]
	UserlandResourceAttributes attr[*string]

	// Debugger attributes
	DebugSessionID attr[*ulid.ULID]
	DebugRunID     attr[*ulid.ULID]

	// AI attributes
	AIRequestMetadata  attr[*aigateway.ParsedInferenceRequest]
	AIResponseMetadata attr[*aigateway.ParsedInferenceResponse]

	Metadata      attr[*metadata.Values]
	MetadataKind  attr[*metadata.Kind]
	MetadataOp    attr[*metadata.Opcode]
	MetadataScope attr[*metadata.Scope]
}{
	internalError: StringAttr("internal.error"),

	AIRequestMetadata:                  JsonAttr[aigateway.ParsedInferenceRequest]("ai.request"),
	AIResponseMetadata:                 JsonAttr[aigateway.ParsedInferenceResponse]("ai.response"),
	AccountID:                          UUIDAttr("account.id"),
	AppID:                              UUIDAttr("app.id"),
	BatchID:                            ULIDAttr("batch.id"),
	BatchTimestamp:                     TimeAttr("batch.ts"),
	CronSchedule:                       StringAttr("cron.schedule"),
	DropSpan:                           BoolAttr("executor.drop"),
	DynamicTraceID:                     StringAttr("dynamic.trace.id"),
	DynamicSpanID:                      StringAttr("dynamic.span.id"),
	DynamicStatus:                      StepStatusAttr("dynamic.status"),
	EndedAt:                            TimeAttr("ended_at"),
	EnvID:                              UUIDAttr("env.id"),
	EventIDs:                           StringSliceAttr("event.ids"),
	EventsInput:                        StringAttr("events.input"),
	TriggeringEventName:                StringAttr("event.trigger.name"),
	FunctionID:                         UUIDAttr("function.id"),
	FunctionVersion:                    IntAttr("function.version"),
	InternalLocation:                   StringAttr("internal.location"),
	IsDurableEndpointRun:               BoolAttr("run.is_durable_endpoint"),
	DurableEndpointModeChangedAt:       TimeAttr("run.durable_endpoint.mode_changed_at"),
	IsFunctionOutput:                   BoolAttr("is.function.output"),
	QueuedAt:                           TimeAttr("queued_at"),
	RequestURL:                         StringAttr("request.url"),
	ResponseHeaders:                    JsonAttr[http.Header]("response.headers"),
	ResponseOutputSize:                 IntAttr("response.output_size"),
	ResponseStatusCode:                 IntAttr("response.status_code"),
	RunID:                              ULIDAttr("run.id"),
	StartedAt:                          TimeAttr("started_at"),
	StepAttempt:                        IntAttr("step.attempt"),
	StepCodeLocation:                   StringAttr("step.code_location"),
	StepGatewayResponseOutputSizeBytes: IntAttr("step.gateway.response.output_size_bytes"),
	StepGatewayResponseStatusCode:      IntAttr("step.gateway.response.status_code"),
	StepHasOutput:                      BoolAttr("step.has_output"),
	Retryable:                          BoolAttr("retryable"),
	StepID:                             StringAttr("step.id"),
	StepInvokeFinishEventID:            ULIDAttr("step.invoke.finish.event.id"),
	StepInvokeFunctionID:               StringAttr("step.invoke.function.id"),
	StepInvokeRunID:                    ULIDAttr("step.invoke.run.id"),
	StepInvokeTriggerEventID:           ULIDAttr("step.invoke.trigger.event.id"),
	StepMaxAttempts:                    IntAttr("step.max_attempts"),
	StepName:                           TruncatedStringAttr("step.name", 128),
	StepOp:                             StepOpAttr("step.op"),
	StepInput:                          StringAttr("step.input"),
	StepOutput:                         StringAttr("step.output"),
	StepOutputRef:                      StringAttr("step.output_ref"),
	StepRunType:                        StringAttr("step.run.type"),
	StepSignalName:                     StringAttr("step.signal.name"),
	StepSleepDuration:                  DurationAttr("step.sleep.duration"),
	StepUserlandID:                     TruncatedStringAttr("step.userland.id", 128),
	StepUserlandIndex:                  IntAttr("step.userland.index"),
	StepWaitExpired:                    BoolAttr("step.wait.expired"),
	StepWaitExpiry:                     TimeAttr("step.wait.expiry"),
	StepWaitForEventIf:                 StringAttr("step.wait_for_event.if"),
	StepWaitForEventMatchedID:          ULIDAttr("step.wait_for_event.matched_id"),
	StepWaitForEventName:               StringAttr("step.wait_for_event.name"),
	UserlandSpanID:                     StringAttr("userland.span.id"),
	IsCheckpoint:                       BoolAttr("checkpoint"),
	IsUserland:                         BoolAttr("userland"),
	UserlandKind:                       StringAttr("userland.kind"),
	UserlandServiceName:                StringAttr("userland.service.name"),
	UserlandScopeName:                  StringAttr("userland.scope.name"),
	UserlandScopeVersion:               StringAttr("userland.scope.version"),
	UserlandResourceAttributes:         StringAttr("userland.resource.attributes"),
	UserlandName:                       StringAttr("userland.name"),
	DebugSessionID:                     ULIDAttr("debug.session.id"),
	DebugRunID:                         ULIDAttr("debug.run.id"),

	Metadata:      JsonAttr[metadata.Values]("metadata.values"),
	MetadataKind:  StringishAttr[metadata.Kind]("metadata.kind"),
	MetadataOp:    TextAttr[enums.MetadataOpcode]("metadata.op"),
	MetadataScope: TextAttr[enums.MetadataScope]("metadata.scope"),
}
