// Code generated by generate_extracted_values.go; DO NOT EDIT.

package meta

import (
	"time"
	
	"github.com/google/uuid"
	"github.com/inngest/inngest/pkg/enums"
	"github.com/oklog/ulid/v2"
)

// ExtractedValues mirrors the Attrs struct but with actual pointer types
// instead of Attr wrappers. This allows for type-safe access to deserialized values.
type ExtractedValues struct {
	StartedAt *time.Time
	QueuedAt *time.Time
	EndedAt *time.Time
	AccountID *uuid.UUID
	AppID *uuid.UUID
	BatchID *ulid.ULID
	BatchTimestamp *time.Time
	CronSchedule *string
	DropSpan *bool
	EnvID *uuid.UUID
	EventIDs *[]string
	FunctionID *uuid.UUID
	FunctionVersion *int
	RunID *ulid.ULID
	DynamicSpanID *string
	DynamicStatus *enums.StepStatus
	InternalLocation *string
	InternalError *string
	StepID *string
	StepName *string
	StepOp *enums.Opcode
	StepAttempt *int
	StepMaxAttempts *int
	StepCodeLocation *string
	StepOutput *any
	StepOutputRef *string
	StepRunType *string
	StepWaitExpired *bool
	StepWaitExpiry *time.Time
	StepInvokeFunctionID *uuid.UUID
	StepInvokeTriggerEventID *string
	StepInvokeFinishEventID *string
	StepInvokeRunID *ulid.ULID
	StepSleepDuration *time.Duration
	StepWaitForEventIf *string
	StepWaitForEventName *string
	StepWaitForEventMatchedID *string
	StepSignalName *string
	StepGatewayResponseStatusCode *int
	StepGatewayResponseOutputSizeBytes *int
	RequestURL *string
	ResponseHeaders *map[string]string
	ResponseStatusCode *int
	ResponseOutputSize *int
}
