// Code generated by generate_extracted_values.go; DO NOT EDIT.

package meta

import (
	"time"

	"github.com/google/uuid"
	"github.com/inngest/inngest/pkg/enums"
	"github.com/inngest/inngest/pkg/headers"
	"github.com/inngest/inngest/pkg/tracing/metadata"
	"github.com/inngest/inngest/pkg/util/aigateway"
	"github.com/oklog/ulid/v2"
)

// ExtractedValues mirrors the Attrs struct but with actual pointer types
// instead of attr wrappers. This allows for type-safe access to deserialized values.
type ExtractedValues struct {
	QueuedAt *time.Time
	ScheduledAt *time.Time
	StartedAt *time.Time
	EndedAt *time.Time
	AccountID *uuid.UUID
	AppID *uuid.UUID
	AppName *string
	BatchID *ulid.ULID
	BatchTimestamp *time.Time
	CronSchedule *string
	DropSpan *bool
	EnvID *uuid.UUID
	EventIDs *[]string
	EventsInput *string
	Sessions *EventSessions
	TriggeringEventName *string
	FunctionID *uuid.UUID
	FunctionName *string
	FunctionSlug *string
	FunctionVersion *int
	RunID *ulid.ULID
	ReplayOriginalRunID *ulid.ULID
	RunScheduleType *enums.ScheduleType
	SkipReason *enums.SkipReason
	SkipExistingRunID *string
	IsDurableEndpointRun *bool
	DurableEndpointModeChangedAt *time.Time
	DeferChildRunID *ulid.ULID
	DeferFnSlug *string
	DeferHashedID *string
	DeferParentFnSlug *string
	DeferParentRunIDs *[]string
	DeferStatus *enums.DeferStatus
	DeferUserlandID *string
	DynamicSpanID *string
	DynamicStatus *enums.StepStatus
	DynamicTraceID *string
	InternalLocation *string
	internalError *string
	IsFunctionOutput *bool
	Retryable *bool
	StepID *string
	StepName *string
	StepOp *enums.Opcode
	StepAttempt *int
	StepMaxAttempts *int
	StepCodeLocation *string
	StepType *enums.StepType
	StepInput *string
	StepOutput *string
	StepOutputRef *string
	StepHasOutput *bool
	StepUserlandID *string
	StepUserlandIndex *int
	StepRunType *string
	ExperimentName *string
	ExperimentStepID *string
	ExperimentVariant *string
	StepWaitExpired *bool
	StepWaitExpiry *time.Time
	StepInvokeFunctionID *string
	StepInvokeTriggerEventID *ulid.ULID
	StepInvokeFinishEventID *ulid.ULID
	StepInvokeRunID *ulid.ULID
	StepSleepDuration *time.Duration
	StepWaitForEventIf *string
	StepWaitForEventName *string
	StepWaitForEventMatchedID *ulid.ULID
	StepSignalName *string
	StepGatewayResponseStatusCode *int
	StepGatewayResponseOutputSizeBytes *int
	RequestID *string
	JobID *string
	GroupID *string
	RequestURL *string
	ResponseHeaders *headers.Compact
	ResponseStatusCode *int
	ResponseOutputSize *int
	ResponseSteps *ResponseOps
	IsCheckpoint *bool
	IsUserland *bool
	UserlandSpanID *string
	UserlandName *string
	UserlandKind *string
	UserlandServiceName *string
	UserlandScopeName *string
	UserlandScopeVersion *string
	UserlandResourceAttributes *string
	DebugSessionID *ulid.ULID
	DebugRunID *ulid.ULID
	AIRequestMetadata *aigateway.ParsedInferenceRequest
	AIResponseMetadata *aigateway.ParsedInferenceResponse
	Metadata *metadata.Values
	MetadataKind *metadata.Kind
	MetadataOp *metadata.Opcode
	MetadataScope *metadata.Scope
}

var AttrsByKey = map[string]Serializer{

	Attrs.QueuedAt.Key(): Attrs.QueuedAt,
	Attrs.ScheduledAt.Key(): Attrs.ScheduledAt,
	Attrs.StartedAt.Key(): Attrs.StartedAt,
	Attrs.EndedAt.Key(): Attrs.EndedAt,
	Attrs.AccountID.Key(): Attrs.AccountID,
	Attrs.AppID.Key(): Attrs.AppID,
	Attrs.AppName.Key(): Attrs.AppName,
	Attrs.BatchID.Key(): Attrs.BatchID,
	Attrs.BatchTimestamp.Key(): Attrs.BatchTimestamp,
	Attrs.CronSchedule.Key(): Attrs.CronSchedule,
	Attrs.DropSpan.Key(): Attrs.DropSpan,
	Attrs.EnvID.Key(): Attrs.EnvID,
	Attrs.EventIDs.Key(): Attrs.EventIDs,
	Attrs.EventsInput.Key(): Attrs.EventsInput,
	Attrs.Sessions.Key(): Attrs.Sessions,
	Attrs.TriggeringEventName.Key(): Attrs.TriggeringEventName,
	Attrs.FunctionID.Key(): Attrs.FunctionID,
	Attrs.FunctionName.Key(): Attrs.FunctionName,
	Attrs.FunctionSlug.Key(): Attrs.FunctionSlug,
	Attrs.FunctionVersion.Key(): Attrs.FunctionVersion,
	Attrs.RunID.Key(): Attrs.RunID,
	Attrs.ReplayOriginalRunID.Key(): Attrs.ReplayOriginalRunID,
	Attrs.RunScheduleType.Key(): Attrs.RunScheduleType,
	Attrs.SkipReason.Key(): Attrs.SkipReason,
	Attrs.SkipExistingRunID.Key(): Attrs.SkipExistingRunID,
	Attrs.IsDurableEndpointRun.Key(): Attrs.IsDurableEndpointRun,
	Attrs.DurableEndpointModeChangedAt.Key(): Attrs.DurableEndpointModeChangedAt,
	Attrs.DeferChildRunID.Key(): Attrs.DeferChildRunID,
	Attrs.DeferFnSlug.Key(): Attrs.DeferFnSlug,
	Attrs.DeferHashedID.Key(): Attrs.DeferHashedID,
	Attrs.DeferParentFnSlug.Key(): Attrs.DeferParentFnSlug,
	Attrs.DeferParentRunIDs.Key(): Attrs.DeferParentRunIDs,
	Attrs.DeferStatus.Key(): Attrs.DeferStatus,
	Attrs.DeferUserlandID.Key(): Attrs.DeferUserlandID,
	Attrs.DynamicSpanID.Key(): Attrs.DynamicSpanID,
	Attrs.DynamicStatus.Key(): Attrs.DynamicStatus,
	Attrs.DynamicTraceID.Key(): Attrs.DynamicTraceID,
	Attrs.InternalLocation.Key(): Attrs.InternalLocation,
	Attrs.internalError.Key(): Attrs.internalError,
	Attrs.IsFunctionOutput.Key(): Attrs.IsFunctionOutput,
	Attrs.Retryable.Key(): Attrs.Retryable,
	Attrs.StepID.Key(): Attrs.StepID,
	Attrs.StepName.Key(): Attrs.StepName,
	Attrs.StepOp.Key(): Attrs.StepOp,
	Attrs.StepAttempt.Key(): Attrs.StepAttempt,
	Attrs.StepMaxAttempts.Key(): Attrs.StepMaxAttempts,
	Attrs.StepCodeLocation.Key(): Attrs.StepCodeLocation,
	Attrs.StepType.Key(): Attrs.StepType,
	Attrs.StepInput.Key(): Attrs.StepInput,
	Attrs.StepOutput.Key(): Attrs.StepOutput,
	Attrs.StepOutputRef.Key(): Attrs.StepOutputRef,
	Attrs.StepHasOutput.Key(): Attrs.StepHasOutput,
	Attrs.StepUserlandID.Key(): Attrs.StepUserlandID,
	Attrs.StepUserlandIndex.Key(): Attrs.StepUserlandIndex,
	Attrs.StepRunType.Key(): Attrs.StepRunType,
	Attrs.ExperimentName.Key(): Attrs.ExperimentName,
	Attrs.ExperimentStepID.Key(): Attrs.ExperimentStepID,
	Attrs.ExperimentVariant.Key(): Attrs.ExperimentVariant,
	Attrs.StepWaitExpired.Key(): Attrs.StepWaitExpired,
	Attrs.StepWaitExpiry.Key(): Attrs.StepWaitExpiry,
	Attrs.StepInvokeFunctionID.Key(): Attrs.StepInvokeFunctionID,
	Attrs.StepInvokeTriggerEventID.Key(): Attrs.StepInvokeTriggerEventID,
	Attrs.StepInvokeFinishEventID.Key(): Attrs.StepInvokeFinishEventID,
	Attrs.StepInvokeRunID.Key(): Attrs.StepInvokeRunID,
	Attrs.StepSleepDuration.Key(): Attrs.StepSleepDuration,
	Attrs.StepWaitForEventIf.Key(): Attrs.StepWaitForEventIf,
	Attrs.StepWaitForEventName.Key(): Attrs.StepWaitForEventName,
	Attrs.StepWaitForEventMatchedID.Key(): Attrs.StepWaitForEventMatchedID,
	Attrs.StepSignalName.Key(): Attrs.StepSignalName,
	Attrs.StepGatewayResponseStatusCode.Key(): Attrs.StepGatewayResponseStatusCode,
	Attrs.StepGatewayResponseOutputSizeBytes.Key(): Attrs.StepGatewayResponseOutputSizeBytes,
	Attrs.RequestID.Key(): Attrs.RequestID,
	Attrs.JobID.Key(): Attrs.JobID,
	Attrs.GroupID.Key(): Attrs.GroupID,
	Attrs.RequestURL.Key(): Attrs.RequestURL,
	Attrs.ResponseHeaders.Key(): Attrs.ResponseHeaders,
	Attrs.ResponseStatusCode.Key(): Attrs.ResponseStatusCode,
	Attrs.ResponseOutputSize.Key(): Attrs.ResponseOutputSize,
	Attrs.ResponseSteps.Key(): Attrs.ResponseSteps,
	Attrs.IsCheckpoint.Key(): Attrs.IsCheckpoint,
	Attrs.IsUserland.Key(): Attrs.IsUserland,
	Attrs.UserlandSpanID.Key(): Attrs.UserlandSpanID,
	Attrs.UserlandName.Key(): Attrs.UserlandName,
	Attrs.UserlandKind.Key(): Attrs.UserlandKind,
	Attrs.UserlandServiceName.Key(): Attrs.UserlandServiceName,
	Attrs.UserlandScopeName.Key(): Attrs.UserlandScopeName,
	Attrs.UserlandScopeVersion.Key(): Attrs.UserlandScopeVersion,
	Attrs.UserlandResourceAttributes.Key(): Attrs.UserlandResourceAttributes,
	Attrs.DebugSessionID.Key(): Attrs.DebugSessionID,
	Attrs.DebugRunID.Key(): Attrs.DebugRunID,
	Attrs.AIRequestMetadata.Key(): Attrs.AIRequestMetadata,
	Attrs.AIResponseMetadata.Key(): Attrs.AIResponseMetadata,
	Attrs.Metadata.Key(): Attrs.Metadata,
	Attrs.MetadataKind.Key(): Attrs.MetadataKind,
	Attrs.MetadataOp.Key(): Attrs.MetadataOp,
	Attrs.MetadataScope.Key(): Attrs.MetadataScope,
}
