package main

import (
	"fmt"
	"sort"
	"strings"
	"unicode"

	openapiv2 "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	generatedFilename = "pkg/api/v2/include_selectors.gen.go"
	generatedPackage  = protogen.GoImportPath("github.com/inngest/inngest/pkg/api/v2")
	endpointPackage   = protogen.GoImportPath("github.com/inngest/inngest/pkg/api/v2/apiv2endpoint")
)

type selectorSpec struct {
	method  string
	values  []string
	aliases map[string]string
}

func main() {
	protogen.Options{}.Run(generate)
}

func generate(plugin *protogen.Plugin) error {
	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	var specs []selectorSpec
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		for _, service := range file.Services {
			for _, method := range service.Methods {
				values := includeValues(method.Desc)
				if len(values) == 0 {
					continue
				}
				spec, err := newSelectorSpec(string(method.Desc.Name()), method.Desc, values)
				if err != nil {
					return err
				}
				specs = append(specs, spec)
			}
		}
	}
	if len(specs) == 0 {
		return nil
	}

	sort.Slice(specs, func(i, j int) bool { return specs[i].method < specs[j].method })
	g := plugin.NewGeneratedFile(generatedFilename, generatedPackage)
	g.P("// Code generated by protoc-gen-inngest-includes. DO NOT EDIT.")
	g.P()
	g.P("package apiv2")
	g.P()
	emitSelectors(g, specs)
	return nil
}

func includeValues(method protoreflect.MethodDescriptor) []string {
	include := method.Input().Fields().ByJSONName("include")
	if include == nil || !include.IsList() || include.Kind() != protoreflect.StringKind {
		return nil
	}
	opts := include.Options()
	if !proto.HasExtension(opts, openapiv2.E_Openapiv2Field) {
		return nil
	}
	schema, _ := proto.GetExtension(opts, openapiv2.E_Openapiv2Field).(*openapiv2.JSONSchema)
	if schema == nil {
		return nil
	}
	return schema.GetEnum()
}

func newSelectorSpec(name string, method protoreflect.MethodDescriptor, values []string) (selectorSpec, error) {
	spec := selectorSpec{method: name, values: append([]string(nil), values...), aliases: map[string]string{}}
	for _, canonical := range values {
		fields := responseFieldsByJSONName(method.Output(), canonical, map[protoreflect.FullName]bool{})
		if len(fields) == 0 {
			return selectorSpec{}, fmt.Errorf("include value %q does not name a response field for %s", canonical, method.Input().FullName())
		}
		if err := spec.add(canonical, canonical); err != nil {
			return selectorSpec{}, err
		}
		for _, field := range fields {
			if err := spec.add(field.TextName(), canonical); err != nil {
				return selectorSpec{}, err
			}
		}
	}
	return spec, nil
}

func (s selectorSpec) add(alias, canonical string) error {
	if existing, ok := s.aliases[alias]; ok && existing != canonical {
		return fmt.Errorf("include value %q is ambiguous for %s", alias, s.method)
	}
	s.aliases[alias] = canonical
	return nil
}

func responseFieldsByJSONName(message protoreflect.MessageDescriptor, name string, visited map[protoreflect.FullName]bool) []protoreflect.FieldDescriptor {
	if visited[message.FullName()] {
		return nil
	}
	visited[message.FullName()] = true

	var matches []protoreflect.FieldDescriptor
	fields := message.Fields()
	for i := 0; i < fields.Len(); i++ {
		field := fields.Get(i)
		if field.JSONName() == name {
			matches = append(matches, field)
		}
		if field.Message() != nil && !field.IsMap() {
			matches = append(matches, responseFieldsByJSONName(field.Message(), name, visited)...)
		}
	}
	return matches
}

func emitSelectors(g *protogen.GeneratedFile, specs []selectorSpec) {
	for _, spec := range specs {
		for _, value := range spec.values {
			g.P("const ", spec.method, "Include", goName(value), " = ", fmt.Sprintf("%q", value))
		}
		g.P()
		g.P("var ", lowerFirst(spec.method), "IncludeSelector = ", g.QualifiedGoIdent(endpointPackage.Ident("NewIncludeSelector")), "(map[string]string{")
		aliases := make([]string, 0, len(spec.aliases))
		for alias := range spec.aliases {
			aliases = append(aliases, alias)
		}
		sort.Strings(aliases)
		for _, alias := range aliases {
			g.P(fmt.Sprintf("%q: %q,", alias, spec.aliases[alias]))
		}
		g.P("})")
		g.P()
	}
}

func goName(value string) string {
	var result strings.Builder
	upper := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper {
			r = unicode.ToUpper(r)
			upper = false
		}
		result.WriteRune(r)
	}
	return result.String()
}

func lowerFirst(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}
