DROP INDEX IF EXISTS idx_spans_name;
DROP INDEX IF EXISTS idx_spans_run_dynamic_end_time;
DROP INDEX IF EXISTS idx_spans_start_time;
DROP INDEX IF EXISTS idx_trace_runs_queued_at;
DROP INDEX IF EXISTS idx_trace_runs_started_at;
DROP INDEX IF EXISTS idx_trace_runs_ended_at;
DROP INDEX IF EXISTS idx_trace_runs_status;
DROP INDEX IF EXISTS idx_trace_runs_app_id;
DROP INDEX IF EXISTS idx_trace_runs_function_id;
