import { renderOperationMarkdown } from "./openapi-to-markdown";
import type { source } from "./source";

type Page = (typeof source)["$inferPage"];

const pretext = `> ## Documentation Index
> Fetch the complete documentation index at: https://api-docs.inngest.com/llms.txt
> Use this file to discover all available pages before exploring further.`;

/**
 * Render a page as Markdown for LLM consumption. Uses the processed Markdown
 * emitted by fumadocs-mdx (enabled via `includeProcessedMarkdown` in
 * source.config.ts) and prepends a heading with the page URL so each entry is
 * self-identifying when concatenated into llms-full.txt.
 *
 * Pages generated from OpenAPI specs only contain an `<APIPage>` JSX element
 * in their MDX body, which the post-processor strips. For those pages we load
 * the operation from the source spec and render it as markdown via
 * `renderOperationMarkdown` so the LLM gets parameters, request bodies, and
 * response schemas instead of an empty body.
 */
export async function getLLMText(page: Page): Promise<string> {
  const [processed, raw] = await Promise.all([
    page.data.getText("processed"),
    page.data.getText("raw"),
  ]);
  const header = `# ${page.data.title} (${page.url})`;
  const description = page.data.description
    ? `> ${page.data.description}\n`
    : "";
  const openapiBody = await renderAPIPages(raw);

  const body = [description, openapiBody, stripGeneratedNoise(processed).trim()]
    .filter(Boolean)
    .join("\n");
  return `${pretext}\n\n${header}\n\n${body}`.trimEnd();
}

/**
 * Drop the boilerplate emitted into OpenAPI-generated MDX:
 *  - the `{/* This file was generated by Fumadocs... *\/}` MDX comment
 *  - the `<APIPage ...>` element itself (its info is surfaced separately via
 *    renderAPIPages).
 */
function stripGeneratedNoise(text: string): string {
  return text
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, "")
    .replace(/<APIPage\b[^>]*\/?>(?:[\s\S]*?<\/APIPage>)?/g, "");
}

const API_PAGE_RE = /<APIPage\b([^>]*)\/>/g;

async function renderAPIPages(raw: string): Promise<string> {
  const sections: string[] = [];
  for (const match of raw.matchAll(API_PAGE_RE)) {
    const attrs = match[1];
    const document = matchAttr(attrs, "document");
    const operations = matchJsonAttr<Array<{ path?: string; method?: string }>>(
      attrs,
      "operations",
    );
    if (!document || !operations) continue;
    for (const op of operations) {
      if (!op.path || !op.method) continue;
      const rendered = await renderOperationMarkdown(
        document,
        op.path,
        op.method,
      );
      if (rendered) sections.push(rendered);
    }
  }
  return sections.join("\n\n");
}

function matchAttr(attrs: string, name: string): string | null {
  // Matches: document={"value"} or document="value"
  const re = new RegExp(
    `\\s${name}=(?:\\{(?:"([^"]*)"|'([^']*)')\\}|"([^"]*)"|'([^']*)')`,
  );
  const m = attrs.match(re);
  if (!m) return null;
  return m[1] ?? m[2] ?? m[3] ?? m[4] ?? null;
}

function matchJsonAttr<T>(attrs: string, name: string): T | null {
  // Matches: operations={[...]}
  const re = new RegExp(`\\s${name}=\\{(\\[.*?\\])\\}`);
  const m = attrs.match(re);
  if (!m) return null;
  try {
    return JSON.parse(m[1]) as T;
  } catch {
    return null;
  }
}
