import type { source } from './source';

type Page = (typeof source)['$inferPage'];

/**
 * Render a page as Markdown for LLM consumption. Uses the processed Markdown
 * emitted by fumadocs-mdx (enabled via `includeProcessedMarkdown` in
 * source.config.ts) and prepends a heading with the page URL so each entry is
 * self-identifying when concatenated into llms-full.txt.
 *
 * Pages generated from OpenAPI specs only contain an `<APIPage>` JSX element
 * in their MDX body, which the post-processor strips. For those pages we pull
 * the method/path out of the raw `<APIPage operations=...>` prop so the LLM
 * still has something concrete to reference.
 */
export async function getLLMText(page: Page): Promise<string> {
  const [processed, raw] = await Promise.all([
    page.data.getText('processed'),
    page.data.getText('raw'),
  ]);
  const header = `# ${page.data.title} (${page.url})`;
  const description = page.data.description ? `> ${page.data.description}\n` : '';
  const openapiSummary = extractOpenAPIOperations(raw);

  const body = [description, openapiSummary, stripGeneratedNoise(processed).trim()]
    .filter(Boolean)
    .join('\n');
  return `${header}\n\n${body}`.trimEnd();
}

/**
 * Drop the boilerplate emitted into OpenAPI-generated MDX:
 *  - the `{/* This file was generated by Fumadocs... *\/}` MDX comment
 *  - the `<APIPage ...>` element itself (its info is surfaced separately via
 *    extractOpenAPIOperations).
 */
function stripGeneratedNoise(text: string): string {
  return text
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
    .replace(/<APIPage\b[^>]*\/?>(?:[\s\S]*?<\/APIPage>)?/g, '');
}

function extractOpenAPIOperations(raw: string): string {
  const match = raw.match(/<APIPage[^>]*\soperations=\{(\[[^\]]*\])\}/);
  if (!match) return '';
  let operations: Array<{ path?: string; method?: string }>;
  try {
    operations = JSON.parse(match[1]);
  } catch {
    return '';
  }
  const lines = operations
    .filter((op): op is { path: string; method: string } => Boolean(op.path && op.method))
    .map((op) => `**${op.method.toUpperCase()} ${op.path}**`);
  return lines.length > 0 ? `${lines.join('\n')}\n` : '';
}
