#!/usr/bin/env bash
#
# Bumps the pinned DuckDB CLI build in pkg/db/duckdb/pinned.go to whatever
# DuckDB's staging server currently reports as the latest alpha build,
# re-downloading each platform's release archive to recompute
# pinnedChecksums. Regenerates pinned.go wholesale (rather than patching it
# in place) so the file always matches its own generator.
#
# See pinned.go's PinnedVersion doc comment for why this package pins a
# nightly/staged build instead of a tagged GA release, and why nightly
# builds can be garbage-collected out from under a stale pin.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="${repo_root}/pkg/db/duckdb/pinned.go"
staging_base="https://duckdb-staging.duckdb.org"

sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    else
        shasum -a 256 "$1" | awk '{print $1}'
    fi
}

echo "Fetching ${staging_base}/latest_alpha_version.txt"
latest="$(curl -sSfL "${staging_base}/latest_alpha_version.txt")"
commit="${latest%%/*}"
version="${latest#*/}"

if [[ -z "${commit}" || -z "${version}" || "${commit}" == "${latest}" ]]; then
    echo "error: unexpected latest_alpha_version.txt format: ${latest}" >&2
    exit 1
fi

echo "Latest staged build: ${version} (commit ${commit})"

base_url="${staging_base}/${commit}/${version}/duckdb/duckdb/github_release/"
assets=(
    "duckdb-cli-osx-universal.tar.gz"
    "duckdb-cli-linux-amd64.tar.gz"
    "duckdb-cli-linux-arm64.tar.gz"
    "duckdb-cli-windows-amd64.tar.gz"
)

workdir="$(mktemp -d)"
trap 'rm -rf "${workdir}"' EXIT

declare -A checksums
for asset in "${assets[@]}"; do
    echo "Downloading ${asset}"
    curl -sSfL "${base_url}${asset}" -o "${workdir}/${asset}"
    checksums["${asset}"]="$(sha256_of "${workdir}/${asset}")"
done

echo "Writing ${target}"
cat >"${target}" <<EOF
// Code generated by scripts/update-duckdb-version.sh. DO NOT EDIT.

package duckdb

// PinnedVersion is the DuckDB CLI build this package downloads and runs
// against. It is a specific nightly/staged build (not a tagged GA release):
// duckdb doesn't publish stable-channel installers for the version this
// driver targets, so EnsureBinary (download.go) fetches it from DuckDB's
// staging distribution server instead — see pinnedStagedCommit and
// defaultInstallBaseURL.
const PinnedVersion = "${version}"

// pinnedStagedCommit is the (10-character, matching DuckDB's own install
// script convention) commit hash PinnedVersion was built from, required to
// address it on the staging server — a bare version string isn't enough to
// resolve a nightly build's URL. \`duckdb --version\` prints this hash
// alongside the version (e.g. "v2.1.0-alpha40409 (Unknown Version)
// ecf3b9fcf1").
//
// Nightly builds are not retained indefinitely; if the staging server has
// since garbage-collected this commit, run
// scripts/update-duckdb-version.sh to bump PinnedVersion,
// pinnedStagedCommit, and pinnedChecksums together to a build that's still
// available.
const pinnedStagedCommit = "${commit}"

// pinnedChecksums are the SHA256 digests of each pinned-version release
// archive EnsureBinary might download, keyed by asset name. Unlike a tagged
// GA release, DuckDB's nightly/staged channel publishes no official
// checksums at all — these were computed by downloading each archive once
// at pin time and hashing it locally. That still lets EnsureBinary fail
// closed on corruption or tampering in transit after this point, the same
// trust model as vendoring a dependency and recording its hash yourself; it
// is not a third-party attestation the way a GA release's published
// checksum would be.
var pinnedChecksums = map[string]string{
	"duckdb-cli-osx-universal.tar.gz": "${checksums[duckdb-cli-osx-universal.tar.gz]}",
	"duckdb-cli-linux-amd64.tar.gz":   "${checksums[duckdb-cli-linux-amd64.tar.gz]}",
	"duckdb-cli-linux-arm64.tar.gz":   "${checksums[duckdb-cli-linux-arm64.tar.gz]}",
	"duckdb-cli-windows-amd64.tar.gz": "${checksums[duckdb-cli-windows-amd64.tar.gz]}",
}
EOF

gofmt -w "${target}"

echo
echo "Pinned DuckDB build updated to ${version} (commit ${commit})."
echo "Review the diff, then run:"
echo "  go build ./pkg/db/duckdb/..."
echo "  go test ./pkg/db/duckdb/..."
