package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/inngest/inngest/pkg/consts"
	"github.com/inngest/inngest/pkg/coreapi/generated"
	"github.com/inngest/inngest/pkg/coreapi/graph/models"
	"github.com/inngest/inngest/pkg/cqrs"
	"github.com/inngest/inngest/pkg/deploy"
	"github.com/inngest/inngest/pkg/enums"
	"github.com/inngest/inngest/pkg/event"
	"github.com/inngest/inngest/pkg/execution"
	"github.com/inngest/inngest/pkg/execution/executor"
	state "github.com/inngest/inngest/pkg/execution/state/v2"
	"github.com/inngest/inngest/pkg/inngest"
	"github.com/inngest/inngest/pkg/run"
	"github.com/inngest/inngest/pkg/telemetry/metrics"
	"github.com/inngest/inngest/pkg/util"
	ulid "github.com/oklog/ulid/v2"
	"go.opentelemetry.io/otel/attribute"
)

// CreateApp is the resolver for the createApp field.
func (r *mutationResolver) CreateApp(ctx context.Context, input models.CreateAppInput) (*cqrs.App, error) {
	// URLs must contain a protocol. If not, add http since very few apps use
	// https during development
	if !strings.Contains(input.URL, "://") {
		input.URL = "http://" + input.URL
	}

	// Normalize the URL so that default ports and localhost variants are
	// unified before deriving the placeholder app ID.
	input.URL = util.NormalizeAppURL(input.URL, false)

	// This ID will not match the app ID after the sync process succeeds. That's
	// because the eventual app ID will use the app name, rather than the URL.
	// But we still need to create a placeholder app with a deterministic ID in
	// the meantime.
	//
	// Ideally the app ID would be the same before and after the SDK ping, but
	// we don't know the app name until after the SDK ping
	appID := inngest.DeterministicAppUUID(input.URL)

	// Create a new app which holds the error message.
	params := cqrs.UpsertAppParams{
		ID:  appID,
		Url: input.URL,
		Error: sql.NullString{
			Valid:  true,
			String: deploy.DeployErrUnreachable.Error(),
		},
	}
	app, _ := r.Data.UpsertApp(ctx, params)

	if res := deploy.Ping(ctx, input.URL, r.ServerKind, r.LocalSigningKey, r.RequireKeys); res.Err != nil {
		return app, res.Err
	}

	<-time.After(100 * time.Millisecond)
	apps, err := r.Data.GetAllApps(ctx, consts.DevServerEnvID)
	if err != nil {
		return nil, err
	}
	for _, app := range apps {
		if app.Url == input.URL {
			return app, nil
		}
	}
	return nil, fmt.Errorf("There was an error creating your app")
}

// UpdateApp is the resolver for the updateApp field.
func (r *mutationResolver) UpdateApp(ctx context.Context, input models.UpdateAppInput) (*cqrs.App, error) {
	return r.Data.UpdateAppURL(ctx, cqrs.UpdateAppURLParams{
		ID:  uuid.MustParse(input.ID),
		Url: input.URL,
	})
}

// DeleteApp is the resolver for the deleteApp field.
func (r *mutationResolver) DeleteApp(ctx context.Context, id string) (string, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return "", err
	}
	if err = r.Data.DeleteApp(ctx, parsedID); err != nil {
		return "", err
	}
	return id, nil
}

// DeleteAppByName is the resolver for the deleteAppByName field.
func (r *mutationResolver) DeleteAppByName(ctx context.Context, name string) (bool, error) {
	apps, err := r.Data.GetApps(ctx, consts.DevServerEnvID, nil)
	if err != nil {
		return false, err
	}

	for _, app := range apps {
		if app.Name == name {
			return true, r.Data.DeleteApp(ctx, app.ID)
		}
	}

	return false, nil
}

// InvokeFunction is the resolver for the invokeFunction field.
func (r *mutationResolver) InvokeFunction(ctx context.Context, data map[string]any, functionSlug string, user map[string]any, debugSessionID *ulid.ULID, debugRunID *ulid.ULID) (*bool, error) {
	evt := event.NewInvocationEvent(event.NewInvocationEventOpts{
		Event: event.Event{
			Data: data,
			User: user,
		},
		FnID:           functionSlug,
		DebugSessionID: debugSessionID,
		DebugRunID:     debugRunID,
	})

	ctx, span := run.NewSpan(ctx,
		run.WithName(consts.OtelSpanInvoke),
		run.WithScope(consts.OtelScopeInvoke),
		run.WithNewRoot(),
		run.WithSpanAttributes(
			attribute.String(consts.OtelSysFunctionSlug, functionSlug),
		),
	)
	defer span.End()

	sent := false
	_, err := r.EventHandler(ctx, &evt.Event, nil)
	if err != nil {
		return &sent, err
	}

	sent = true
	return &sent, nil
}

// TODO: Refactor to share logic with the `DELETE /v1/runs/{runID}` REST
// endpoint
func (r *mutationResolver) CancelRun(ctx context.Context, runID ulid.ULID) (*models.FunctionRun, error) {
	accountID := consts.DevServerAccountID
	workspaceID := consts.DevServerEnvID
	run, err := r.HistoryReader.GetFunctionRun(
		ctx,
		accountID,
		workspaceID,
		runID,
	)
	if err != nil {
		return nil, err
	}
	if run.Status == enums.RunStatusCancelled {
		// Already cancelled, so return the run as is. This makes the mutation
		// idempotent
		return models.MakeFunctionRun(run), nil
	}
	if run.EndedAt != nil {
		return nil, errors.New("cannot cancel an ended run")
	}

	id := state.ID{
		RunID:      runID,
		FunctionID: run.FunctionID,
	}

	err = r.Executor.Cancel(ctx, id, execution.CancelRequest{})
	if err != nil {
		return nil, err
	}

	// Wait an arbitrary amount of time to give the history store enough time to
	// reflect the cancellation
	<-time.After(500 * time.Millisecond)

	// Fetch the updated run from the history store, but we need to include
	// polling since the history store is eventually consistent. The history
	// store should reflect cancellation almost immediately, but it might take a
	// noticeable amount of time to update.
	//
	// We probably wouldn't need to poll if our UI used a normalized cache,
	// since we could pseudo-update the status and endedAt fields before
	// returning data
	start := time.Now()
	timeout := 5 * time.Second
	for {
		if time.Since(start) > timeout {
			// Give up and return the run as is. Don't return an error because
			// the run was still cancelled; it's just that the history store
			// wasn't updated fast enough
			return models.MakeFunctionRun(run), nil
		}

		run, err = r.HistoryReader.GetFunctionRun(
			ctx,
			accountID,
			workspaceID,
			runID,
		)
		if err != nil {
			return nil, err
		}

		if run.Status == enums.RunStatusCancelled {
			return models.MakeFunctionRun(run), nil
		}

		<-time.After(time.Second)
	}
}

// Rerun is the resolver for the rerun field.
func (r *mutationResolver) Rerun(ctx context.Context, runID ulid.ULID, fromStep *models.RerunFromStepInput, debugSessionID *ulid.ULID, debugRunID *ulid.ULID) (ulid.ULID, error) {
	accountID := consts.DevServerAccountID
	workspaceID := consts.DevServerEnvID

	fnrun, err := r.Data.GetFunctionRun(
		ctx,
		accountID,
		workspaceID,
		runID,
	)
	if err != nil {
		return ulid.Zero, err
	}

	fnCQRS, err := r.Data.GetFunctionByInternalUUID(
		ctx,
		fnrun.FunctionID,
	)
	if err != nil {
		return ulid.Zero, err
	}

	fn, err := fnCQRS.InngestFunction()
	if err != nil {
		return ulid.Zero, err
	}

	evt, err := r.Data.GetEventByInternalID(ctx, fnrun.EventID)
	if err != nil {
		return ulid.Zero, fmt.Errorf("failed to get run event: %w", err)
	}

	ctx, span := run.NewSpan(ctx,
		run.WithName(consts.OtelSpanRerun),
		run.WithScope(consts.OtelScopeRerun),
		run.WithNewRoot(),
		run.WithSpanAttributes(
			attribute.String(consts.OtelSysAppID, fnCQRS.AppID.String()),
			attribute.String(consts.OtelSysFunctionID, fn.ID.String()),
			attribute.String(consts.OtelSysFunctionSlug, fnCQRS.Slug),
			attribute.String(consts.OtelSysEventIDs, evt.GetInternalID().String()),
		),
	)
	defer span.End()

	var fromStepReq *execution.ScheduleRequestFromStep
	if fromStep != nil {
		fromStepReq = &execution.ScheduleRequestFromStep{
			StepID: fromStep.StepID,
		}

		if fromStep.Input != nil {
			if len(*fromStep.Input) == 0 || (*fromStep.Input)[0] != '[' {
				return ulid.Zero, fmt.Errorf("input is not a valid JSON array")
			}

			fromStepReq.Input = json.RawMessage(*fromStep.Input)
		}
	}

	//
	// preserve the original run ID to support n+1 subsequent reruns from step
	originalRunID := &fnrun.RunID
	if fnrun.OriginalRunID != nil {
		originalRunID = fnrun.OriginalRunID
	}

	newRunID, _, err := r.Executor.Schedule(ctx, execution.ScheduleRequest{
		Function: *fn,
		AppID:    fnCQRS.AppID,
		Events: []event.TrackedEvent{
			// We need NewBaseTrackedEventWithID to ensure that the tracked event
			// has the same ID as the original event. Calling NewBaseTrackedEvent
			// will result in the creation of a new ID
			event.NewBaseTrackedEventWithID(evt.Event(), evt.InternalID()),
		},
		OriginalRunID:  originalRunID,
		AccountID:      consts.DevServerAccountID,
		FromStep:       fromStepReq,
		WorkspaceID:    consts.DevServerEnvID,
		DebugSessionID: debugSessionID,
		DebugRunID:     debugRunID,
		// NOTE: Bypass rate limits for reruns, as the user explicitly expects this to trigger
		PreventRateLimit: true,
	})

	metrics.IncrExecutorScheduleCount(ctx, metrics.CounterOpt{
		PkgName: pkgName,
		Tags: map[string]any{
			"type":   "rerun",
			"status": executor.ScheduleStatus(err),
		},
	})

	if err != nil {
		return ulid.Zero, err
	}

	return *newRunID, nil
}

// CreateDebugSession is the resolver for the createDebugSession field.
func (r *mutationResolver) CreateDebugSession(ctx context.Context, input models.CreateDebugSessionInput) (*models.CreateDebugSessionResponse, error) {
	return &models.CreateDebugSessionResponse{
		DebugSessionID: ulid.Make(),
		DebugRunID:     ulid.Make(),
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
