package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"sort"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/graph-gophers/dataloader"
	"github.com/inngest/inngest/pkg/consts"
	"github.com/inngest/inngest/pkg/coreapi/generated"
	loader "github.com/inngest/inngest/pkg/coreapi/graph/loaders"
	"github.com/inngest/inngest/pkg/coreapi/graph/models"
	"github.com/inngest/inngest/pkg/cqrs"
	"github.com/inngest/inngest/pkg/history_reader"
	"github.com/inngest/inngest/pkg/logger"
	ulid "github.com/oklog/ulid/v2"
)

// Apps is the resolver for the apps field.
func (r *queryResolver) Apps(ctx context.Context, filter *models.AppsFilterV1) ([]*cqrs.App, error) {
	cqrsFilter, err := models.FromAppsFilter(filter)
	if err != nil {
		return nil, fmt.Errorf("failed to parse filter: %w", err)
	}
	return r.Data.GetApps(ctx, consts.DevServerEnvID, cqrsFilter)
}

// App is the resolver for the app field.
func (r *queryResolver) App(ctx context.Context, id uuid.UUID) (*cqrs.App, error) {
	return r.Data.GetAppByID(ctx, id)
}

// Stream is the resolver for the stream field.
func (r *queryResolver) Stream(ctx context.Context, query models.StreamQuery) ([]*models.StreamItem, error) {
	var before *ulid.ULID
	var after *ulid.ULID

	if query.Before != nil {
		val := ulid.MustParse(*query.Before)
		before = &val
	}

	if query.After != nil {
		val := ulid.MustParse(*query.After)
		after = &val
	}

	bound := cqrs.IDBound{
		Before: before,
		After:  after,
	}

	includeInternalEvents := false
	if query.IncludeInternalEvents != nil {
		includeInternalEvents = *query.IncludeInternalEvents
	}

	evts, err := r.Data.GetEventsIDbound(
		ctx,
		bound,
		query.Limit,
		includeInternalEvents,
	)
	if err != nil {
		return nil, err
	}

	ids := make([]ulid.ULID, len(evts))
	for n, evt := range evts {
		ids[n] = evt.InternalID()
	}

	accountID := consts.DevServerAccountID
	workspaceID := consts.DevServerEnvID

	fns, err := r.HistoryReader.GetFunctionRunsFromEvents(
		ctx,
		accountID,
		workspaceID,
		ids,
	)
	if err != nil {
		return nil, err
	}
	fnsByID := map[ulid.ULID][]*models.FunctionRun{}
	for _, fn := range fns {
		run := models.MakeFunctionRun(fn)
		_, err := r.Data.GetFunctionByInternalUUID(ctx, uuid.MustParse(run.FunctionID))
		if err == sql.ErrNoRows {
			// Skip run since its function doesn't exist. This can happen when
			// deleting a function or changing its ID.
			continue
		}

		fnsByID[fn.EventID] = append(fnsByID[fn.EventID], run)
	}

	items := make([]*models.StreamItem, len(evts))
	for n, i := range evts {
		items[n] = &models.StreamItem{
			ID:        i.ID.String(),
			Trigger:   i.EventName,
			Type:      models.StreamTypeEvent,
			CreatedAt: time.UnixMilli(i.EventTS),
			Runs:      []*models.FunctionRun{},
		}

		runs := fnsByID[i.ID]
		if len(runs) > 0 {
			// If any of the runs is a cron, then the stream item is a cron
			for _, run := range runs {
				if run.Cron != nil && *run.Cron != "" {
					items[n].Trigger = *run.Cron
					items[n].Type = models.StreamTypeCron
					break
				}
			}

			items[n].Runs = runs
		}
	}

	sort.Slice(items, func(i, j int) bool {
		return items[i].CreatedAt.After(items[j].CreatedAt)
	})

	if len(items) > query.Limit {
		return items[0:query.Limit], nil
	}

	return items, nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, query models.EventQuery) (*models.Event, error) {
	id, _ := ulid.Parse(query.EventID)

	evt, err := r.Data.GetEventByInternalID(ctx, id)
	if err != nil {
		return nil, err
	}

	payloadByt, err := json.Marshal(evt.EventData)
	if err != nil {
		return nil, err
	}
	payload := string(payloadByt)

	createdAt := time.UnixMilli(evt.EventTS)
	if evt.EventTS == 0 {
		createdAt = ulid.Time(evt.ID.Time())
	}

	var externalID *string
	if evt.EventID != "" {
		externalID = &evt.EventID
	}

	return &models.Event{
		ID:         evt.InternalID(),
		ExternalID: externalID,
		Name:       &evt.EventName,
		CreatedAt:  &createdAt,
		Payload:    &payload,
	}, nil
}

// deprecated
func (r *queryResolver) Events(ctx context.Context, query models.EventsQuery) ([]*models.Event, error) {
	opts := &cqrs.WorkspaceEventsOpts{
		Limit: cqrs.MaxEvents,
	}

	loaded, err := r.Data.GetEvents(ctx, consts.DevServerAccountID, consts.DevServerEnvID, opts)
	if err != nil {
		return nil, err
	}

	var events []*models.Event

	for _, evt := range loaded {
		name := evt.EventName

		createdAt := time.UnixMilli(evt.EventTS)
		if evt.EventTS == 0 {
			if id, err := ulid.Parse(evt.EventID); err == nil {
				createdAt = ulid.Time(id.Time())
			}
		}

		payloadByt, err := json.Marshal(evt.EventData)
		if err != nil {
			continue
		}
		payload := string(payloadByt)

		internalID, err := ulid.Parse(evt.EventID)
		if err != nil {
			continue
		}

		events = append(events, &models.Event{
			ID:        internalID,
			Name:      &name,
			CreatedAt: &createdAt,
			Payload:   &payload,
		})
	}

	sort.Slice(events, func(i, j int) bool {
		return events[i].ID.String() > events[j].ID.String()
	})

	return events, nil
}

// EventV2 is the resolver for the eventV2 field.
func (r *queryResolver) EventV2(ctx context.Context, id ulid.ULID) (*models.EventV2, error) {
	targetLoader := loader.FromCtx(ctx).EventLoader

	event, err := loader.LoadOneWithString[cqrs.Event](
		ctx,
		targetLoader,
		id.String(),
	)

	if err != nil {
		return nil, err
	}

	return cqrsEventToGQLEvent(event), nil
}

// EventsV2 is the resolver for the eventsV2 field.
func (r *queryResolver) EventsV2(ctx context.Context, first int, after *string, filter models.EventsFilter) (*models.EventsConnection, error) {
	pageSize := defaultPageSize
	if first > 0 && first <= cqrs.MaxEvents {
		pageSize = first
	}

	opts := &cqrs.WorkspaceEventsOpts{
		Limit: pageSize,
		Names: filter.EventNames,
	}

	cursor := &EventsV2ConnectionCursor{}
	if after != nil && *after != "" {
		if err := cursor.Decode(*after); err != nil {
			return nil, fmt.Errorf("error decoding eventsv2 cursor: %w", err)
		}
		if cursor.ID != "" {
			parsed, err := ulid.Parse(cursor.ID)
			if err != nil {
				return nil, fmt.Errorf("error parsing eventsv2 cursor: %w", err)
			}
			opts.Cursor = &parsed
		}
	}

	opts.IncludeInternalEvents = filter.IncludeInternalEvents

	opts.Oldest = filter.From

	// If we don't have a cursor, fetch the latest events
	// otherwise this has no impact
	opts.Newest = time.Now()

	if filter.Until != nil {
		opts.Newest = *filter.Until
	}

	events, err := r.Data.GetEvents(ctx, consts.DevServerAccountID, consts.DevServerEnvID, opts)
	if err != nil {
		return nil, err
	}

	targetLoader := loader.FromCtx(ctx).EventLoader

	eventEdges := []*models.EventsEdge{}
	for _, e := range events {
		targetLoader.Prime(ctx, dataloader.StringKey(e.InternalID().String()), e)

		eventV2 := cqrsEventToGQLEvent(e)

		cursorByt, err := json.Marshal(EventsV2ConnectionCursor{ID: eventV2.ID.String()})
		if err != nil {
			return nil, err
		}

		eventEdges = append(eventEdges, &models.EventsEdge{
			Node:   eventV2,
			Cursor: base64.StdEncoding.EncodeToString(cursorByt),
		})
	}

	// somewhat inaccurate if the last page has exactly the number of entries requested,
	// but the next page will just be a page with 0 and hasNextPage = false
	hasNextPage := len(eventEdges) == first

	var startCursor, endCursor *string
	if len(eventEdges) > 0 {
		startCursor = &(eventEdges[0].Cursor)
		endCursor = &(eventEdges[len(eventEdges)-1].Cursor)
	}

	return &models.EventsConnection{
		Edges: eventEdges,
		PageInfo: &models.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: after != nil, // accurate as long as clients always send null cursor for first page
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}

// FunctionBySlug is the resolver for the functionBySlug field.
func (r *queryResolver) FunctionBySlug(ctx context.Context, query models.FunctionQuery) (*models.Function, error) {
	fn, err := r.Data.GetFunctionByExternalID(ctx, consts.DevServerEnvID, "local", query.FunctionSlug)
	if err != nil {
		return nil, err
	}
	return models.MakeFunction(fn)
}

// Functions is the resolver for the functions field.
func (r *queryResolver) Functions(ctx context.Context) ([]*models.Function, error) {
	all, err := r.Data.GetFunctions(ctx)
	if err != nil {
		return nil, err
	}
	res := make([]*models.Function, len(all))
	for n, i := range all {
		res[n], err = models.MakeFunction(i)
		if err != nil {
			return nil, err
		}
	}
	return res, nil
}

// FunctionRun is the resolver for the functionRun field.
func (r *queryResolver) FunctionRun(ctx context.Context, query models.FunctionRunQuery) (*models.FunctionRun, error) {
	if query.FunctionRunID == "" {
		return nil, fmt.Errorf("function run id is required")
	}

	runID, err := ulid.Parse(query.FunctionRunID)
	if err != nil {
		return nil, fmt.Errorf("invalid run ID: %w", err)
	}

	run, err := r.HistoryReader.GetRun(
		ctx,
		runID,
		history_reader.GetRunOpts{},
	)
	if err != nil {
		return nil, err
	}

	status, err := models.ToFunctionRunStatus(run.Status)
	if err != nil {
		return nil, err
	}

	return &models.FunctionRun{
		ID:         runID.String(),
		FunctionID: run.WorkflowID.String(),
		FinishedAt: run.EndedAt,
		StartedAt:  &run.StartedAt,
		EventID:    run.EventID.String(),
		BatchID:    run.BatchID,
		Status:     &status,
		Output:     run.Output,
	}, nil
}

// Runs is the resolver for the runs field.
func (r *queryResolver) Runs(ctx context.Context, first int, after *string, orderBy []*models.RunsV2OrderBy, filter models.RunsFilterV2, preview *bool) (*models.RunsV2Connection, error) {
	opts := toRunsQueryOpt(first, after, orderBy, filter, preview)
	runs, err := r.Data.GetTraceRuns(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("error retrieving runs: %w", err)
	}

	var (
		scursor *string
		ecursor *string
	)
	// eventID to run map
	evtRunMap := map[ulid.ULID][]*models.FunctionRunV2{}
	// used for retrieving eventIDs
	evtIDs := []ulid.ULID{}

	edges := []*models.FunctionRunV2Edge{}
	total := len(runs)
	for i, r := range runs {
		var (
			started   *time.Time
			ended     *time.Time
			sourceID  *string
			output    *string
			batchTime *time.Time
		)

		c := r.Cursor
		if i == 0 {
			scursor = &c // start cursor
		}
		if i == total-1 {
			ecursor = &c // end cursor
		}

		if r.StartedAt.UnixMilli() > 0 {
			started = &r.StartedAt
		}
		if r.EndedAt.UnixMilli() > 0 {
			ended = &r.EndedAt
		}
		if len(r.SourceID) > 0 {
			sourceID = &r.SourceID
		}
		if len(r.Output) > 0 {
			s := string(r.Output)
			output = &s
		}

		// If this run ID is the same as the starting cursor, do not include it.
		if scursor != nil && r.RunID == *scursor {
			continue
		}

		runID := ulid.MustParse(r.RunID)
		status, err := models.ToFunctionRunStatus(r.Status)
		if err != nil {
			continue
		}

		if r.BatchID != nil {
			ts := ulid.Time(r.BatchID.Time())
			batchTime = &ts
		}

		node := &models.FunctionRunV2{
			ID:             runID,
			AppID:          r.AppID,
			FunctionID:     r.FunctionID,
			TraceID:        r.TraceID,
			QueuedAt:       r.QueuedAt,
			StartedAt:      started,
			EndedAt:        ended,
			SourceID:       sourceID,
			Status:         status,
			Output:         output,
			IsBatch:        r.IsBatch,
			BatchCreatedAt: batchTime,
			CronSchedule:   r.CronSchedule,
			HasAi:          r.HasAI,
		}

		triggerIDS := []ulid.ULID{}
		for _, tid := range r.TriggerIDs {
			if id, err := ulid.Parse(tid); err == nil {
				triggerIDS = append(triggerIDS, id)

				// track evtID only if it's not batch nor cron
				if !r.IsBatch && r.CronSchedule == nil {
					if _, ok := evtRunMap[id]; !ok {
						evtRunMap[id] = []*models.FunctionRunV2{}
					}
					evtRunMap[id] = append(evtRunMap[id], node)
					evtIDs = append(evtIDs, id)
				}
			}
		}

		node.TriggerIDs = triggerIDS

		edges = append(edges, &models.FunctionRunV2Edge{
			Node:   node,
			Cursor: r.Cursor,
		})
	}

	evts, err := r.Data.GetEventsByInternalIDs(ctx, evtIDs)
	if err != nil {
		return nil, fmt.Errorf("error retrieving events associated with runs: %w", err)
	}
	var wg sync.WaitGroup
	for _, e := range evts {
		wg.Add(1)
		go func(evt *cqrs.Event) {
			defer wg.Done()

			runs, ok := evtRunMap[evt.GetInternalID()]
			if !ok {
				return
			}
			for _, run := range runs {
				run.EventName = &evt.EventName
			}
		}(e)
	}
	wg.Wait()

	pageInfo := &models.PageInfo{
		HasNextPage: total == int(opts.Items),
		StartCursor: scursor,
		EndCursor:   ecursor,
	}

	return &models.RunsV2Connection{
		Edges:    edges,
		PageInfo: pageInfo,
		After:    after,
		Filter:   filter,
		OrderBy:  orderBy,
	}, nil
}

// Run is the resolver for the run field.
func (r *queryResolver) Run(ctx context.Context, runID string) (*models.FunctionRunV2, error) {
	runid, err := ulid.Parse(runID)
	if err != nil {
		return nil, fmt.Errorf("error parsing runID: %w", err)
	}

	run, err := r.Data.GetTraceRun(ctx, cqrs.TraceRunIdentifier{RunID: runid})
	if err != nil {
		return nil, fmt.Errorf("error retrieving run: %w", err)
	}

	var (
		startedAt *time.Time
		endedAt   *time.Time
		sourceID  *string
		output    *string
		batchTS   *time.Time
	)

	triggerIDs := []ulid.ULID{}
	for _, evtID := range run.TriggerIDs {
		if id, err := ulid.Parse(evtID); err == nil {
			triggerIDs = append(triggerIDs, id)
		}
	}

	if len(run.Output) > 0 {
		o := string(run.Output)
		output = &o
	}

	if run.BatchID != nil {
		ts := ulid.Time(run.BatchID.Time())
		batchTS = &ts
	}

	status, err := models.ToFunctionRunStatus(run.Status)
	if err != nil {
		return nil, fmt.Errorf("error parsing status: %w", err)
	}

	if run.StartedAt.UnixMilli() > 0 {
		startedAt = &run.StartedAt
	}
	if run.SourceID != "" {
		sourceID = &run.SourceID
	}

	switch status {
	case models.FunctionRunStatusCompleted, models.FunctionRunStatusFailed, models.FunctionRunStatusCancelled:
		if run.EndedAt.UnixMilli() > 0 {
			endedAt = &run.EndedAt
		}
	}

	res := models.FunctionRunV2{
		ID:             runid,
		AppID:          run.AppID,
		FunctionID:     run.FunctionID,
		TraceID:        run.TraceID,
		QueuedAt:       run.QueuedAt,
		StartedAt:      startedAt,
		EndedAt:        endedAt,
		Status:         status,
		SourceID:       sourceID,
		TriggerIDs:     triggerIDs,
		IsBatch:        run.IsBatch,
		BatchCreatedAt: batchTS,
		CronSchedule:   run.CronSchedule,
		Output:         output,
		HasAi:          run.HasAI,
	}

	return &res, nil
}

// RunTraceSpanOutputByID is the resolver for the runTraceSpanOutputByID field.
func (r *queryResolver) RunTraceSpanOutputByID(ctx context.Context, outputID string) (*models.RunTraceSpanOutput, error) {
	id := &cqrs.SpanIdentifier{}
	if err := id.Decode(outputID); err != nil {
		return nil, fmt.Errorf("error parsing span identifier: %w", err)
	}

	var (
		spanData *cqrs.SpanOutput
		err      error
	)

	if id.Preview == nil || !*id.Preview {
		spanData, err = r.Data.LegacyGetSpanOutput(ctx, *id)
	} else {
		spanData, err = r.Data.GetSpanOutput(ctx, *id)
	}
	if err != nil {
		return nil, err
	}

	resp := models.RunTraceSpanOutput{}
	if spanData.IsError {
		var stepErr models.StepError
		err := json.Unmarshal(spanData.Data, &stepErr)
		if err != nil {
			logger.StdlibLogger(ctx).Error("error deserializing step error", "error", err)

			// This may have been the `cause`, as that's any JSON value, but
			// needs to be a string when parsed here. Let's try to save it.
			if stepErr.Cause == nil {
				var rawErr map[string]any
				if err := json.Unmarshal(spanData.Data, &rawErr); err == nil {
					var causeStr *string
					if cause, ok := rawErr["cause"]; ok {
						if byt, err := json.Marshal(cause); err == nil {
							s := string(byt)
							causeStr = &s
						}
					}

					stepErr.Cause = causeStr
				}
			}
		}

		if stepErr.Message == "" {
			stack := string(spanData.Data)
			stepErr.Stack = &stack
		}

		resp.Error = &stepErr
	} else {
		d := string(spanData.Data)
		resp.Data = &d
	}

	if len(spanData.Input) > 0 {
		input := string(spanData.Input)
		resp.Input = &input
	}

	return &resp, nil
}

// RunTrigger is the resolver for the runTrigger field.
func (r *queryResolver) RunTrigger(ctx context.Context, runID string) (*models.RunTraceTrigger, error) {
	runid, err := ulid.Parse(runID)
	if err != nil {
		return nil, fmt.Errorf("error parsing runID: %w", err)
	}

	run, err := r.Data.GetTraceRun(ctx, cqrs.TraceRunIdentifier{RunID: runid})
	if err != nil {
		return nil, fmt.Errorf("error retrieving run: %w", err)
	}

	var (
		evtName *string
		ts      time.Time
	)

	evtIDs := []ulid.ULID{}
	for _, id := range run.TriggerIDs {
		if evtID, err := ulid.Parse(id); err == nil {
			evtIDs = append(evtIDs, evtID)

			// use the earliest
			evtTime := ulid.Time(evtID.Time())
			if ts.IsZero() {
				ts = evtTime
			}
			if evtTime.Before(ts) {
				ts = evtTime
			}
		}
	}

	events, err := r.Data.GetEventsByInternalIDs(ctx, evtIDs)
	if err != nil {
		return nil, fmt.Errorf("error retrieving events: %w", err)
	}

	payloads := []string{}
	for _, evt := range events {
		byt, err := json.Marshal(evt.GetEvent())
		if err != nil {
			return nil, fmt.Errorf("error parsing event payload: %w", err)
		}
		payloads = append(payloads, string(byt))
	}

	// only parse event name if it's not cron
	if run.CronSchedule == nil {
		// just need the first one
		var name string
		for _, evt := range events {
			if name == "" {
				name = evt.EventName
			}
			// finish early if  it's not a batch and there's already a value
			if run.BatchID == nil && name != "" {
				break
			}

			// if there are multiple events and they are not identical,
			// set event name to nil
			if evt.EventName != name {
				name = ""
				break
			}
		}

		if name != "" {
			evtName = &name
		}
	}

	resp := models.RunTraceTrigger{
		EventName: evtName,
		Timestamp: ts,
		IDs:       evtIDs,
		Payloads:  payloads,
		BatchID:   run.BatchID,
		IsBatch:   run.BatchID != nil,
		Cron:      run.CronSchedule,
	}

	return &resp, nil
}

// RunTrace is the resolver for the runTrace field.
func (r *queryResolver) RunTrace(ctx context.Context, runID string) (*models.RunTraceSpan, error) {
	runid, err := ulid.Parse(runID)
	if err != nil {
		return nil, fmt.Errorf("error parsing runID: %w", err)
	}

	span, err := loader.LoadOne[models.RunTraceSpan](
		ctx,
		loader.FromCtx(ctx).RunTraceLoader,
		&loader.TraceRequestKey{TraceRunIdentifier: &cqrs.TraceRunIdentifier{RunID: runid}},
	)
	if err != nil {
		return nil, err
	}
	if span == nil {
		return nil, fmt.Errorf("run trace not found")
	}
	return span, nil
}

// DebugRun is the resolver for the debugRun field.
func (r *queryResolver) DebugRun(ctx context.Context, query models.DebugRunQuery) (*models.DebugRun, error) {
	var debugRunSpans []*models.RunTraceSpan

	if query.DebugRunID != nil {
		debugRunID, err := ulid.Parse(*query.DebugRunID)
		if err != nil {
			return nil, fmt.Errorf("invalid debugRunID: %w", err)
		}

		spans, err := loader.LoadOne[[]*models.RunTraceSpan](
			ctx,
			loader.FromCtx(ctx).DebugRunLoader,
			&loader.DebugRunRequestKey{
				DebugRunID: debugRunID,
			},
		)
		if err != nil {
			return nil, err
		}
		if spans != nil {
			debugRunSpans = *spans
		}

	}

	return &models.DebugRun{
		DebugTraces: debugRunSpans,
	}, nil
}

// DebugSession is the resolver for the debugSession field.
func (r *queryResolver) DebugSession(ctx context.Context, query models.DebugSessionQuery) (*models.DebugSession, error) {
	if query.DebugSessionID != nil {
		debugSessionID, err := ulid.Parse(*query.DebugSessionID)
		if err != nil {
			return nil, fmt.Errorf("invalid debugSessionID: %w", err)
		}

		debugSession, err := loader.LoadOne[*models.DebugSession](
			ctx,
			loader.FromCtx(ctx).DebugSessionLoader,
			&loader.DebugSessionRequestKey{
				DebugSessionID: debugSessionID,
			},
		)
		if err != nil {
			return nil, err
		}

		return *debugSession, nil
	}

	return nil, fmt.Errorf("debug session not found")
}

// WorkerConnections is the resolver for the workerConnections field.
func (r *queryResolver) WorkerConnections(ctx context.Context, first int, after *string, orderBy []*models.ConnectV1WorkerConnectionsOrderBy, filter models.ConnectV1WorkerConnectionsFilter) (*models.WorkerConnectionsConnection, error) {
	opts := toWorkerConnectionsQueryOpt(first, after, orderBy, filter)
	workerConns, err := r.Data.GetWorkerConnections(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("error retrieving worker connections: %w", err)
	}

	var (
		scursor *string
		ecursor *string
	)

	edges := []*models.ConnectV1WorkerConnectionEdge{}
	total := len(workerConns)
	for i, conn := range workerConns {
		c := conn.Cursor
		if i == 0 {
			scursor = &c // start cursor
		}
		if i == total-1 {
			ecursor = &c // end cursor
		}

		edges = append(edges, &models.ConnectV1WorkerConnectionEdge{
			Node:   connToNode(conn),
			Cursor: conn.Cursor,
		})
	}

	pageInfo := &models.PageInfo{
		HasNextPage: total == int(opts.Items),
		StartCursor: scursor,
		EndCursor:   ecursor,
	}

	return &models.WorkerConnectionsConnection{
		Edges:    edges,
		PageInfo: pageInfo,
		After:    after,
		Filter:   filter,
		OrderBy:  orderBy,
	}, nil
}

// WorkerConnection is the resolver for the workerConnection field.
func (r *queryResolver) WorkerConnection(ctx context.Context, connectionID ulid.ULID) (*models.ConnectV1WorkerConnection, error) {
	conn, err := r.Data.GetWorkerConnection(ctx, cqrs.WorkerConnectionIdentifier{
		AccountID:    consts.DevServerAccountID,
		WorkspaceID:  consts.DevServerEnvID,
		ConnectionID: connectionID,
	})
	if err != nil {
		return nil, fmt.Errorf("error retrieving worker connection: %w", err)
	}

	return connToNode(conn), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
