package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/inngest/inngest/pkg/consts"
	"github.com/inngest/inngest/pkg/coreapi/generated"
	loader "github.com/inngest/inngest/pkg/coreapi/graph/loaders"
	"github.com/inngest/inngest/pkg/coreapi/graph/models"
	"github.com/inngest/inngest/pkg/cqrs"
	"github.com/inngest/inngest/pkg/devserver/discovery"
	"github.com/inngest/inngest/pkg/enums"
	statev1 "github.com/inngest/inngest/pkg/execution/state"
	"github.com/inngest/inngest/pkg/history_reader"
	"github.com/inngest/inngest/pkg/inngest"
	"github.com/inngest/inngest/pkg/util"
	ulid "github.com/oklog/ulid/v2"
)

// ID is the resolver for the id field.
func (r *appResolver) ID(ctx context.Context, obj *cqrs.App) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("no app defined")
	}
	return obj.ID.String(), nil
}

// ExternalID is the resolver for the externalID field.
func (r *appResolver) ExternalID(ctx context.Context, obj *cqrs.App) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("no app defined")
	}

	// Name is currently the same as external ID, but we'll eventually allow
	// apps to have names (similar to functions)
	return obj.Name, nil
}

// Framework is the resolver for the framework field.
func (r *appResolver) Framework(ctx context.Context, obj *cqrs.App) (*string, error) {
	if obj == nil {
		return nil, fmt.Errorf("no app defined")
	}
	if obj.Framework.Valid {
		return &obj.Framework.String, nil
	}
	return nil, nil
}

// Error is the resolver for the error field.
func (r *appResolver) Error(ctx context.Context, obj *cqrs.App) (*string, error) {
	if obj == nil {
		return nil, fmt.Errorf("no app defined")
	}
	if obj.Error.Valid {
		return &obj.Error.String, nil
	}
	return nil, nil
}

// Functions is the resolver for the functions field.
func (r *appResolver) Functions(ctx context.Context, obj *cqrs.App) ([]*models.Function, error) {
	if obj == nil {
		return nil, fmt.Errorf("no app defined")
	}
	// Local dev doesn't have a workspace ID.
	funcs, err := r.Data.GetFunctionsByAppInternalID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	res := make([]*models.Function, len(funcs))
	for n, f := range funcs {
		res[n], err = models.MakeFunction(f)
		if err != nil {
			return nil, err
		}

	}
	return res, nil
}

// Method is the resolver for the method field.
func (r *appResolver) Method(ctx context.Context, obj *cqrs.App) (models.AppMethod, error) {
	method, err := enums.AppMethodString(obj.Method)
	if err != nil {
		return models.AppMethodServe, fmt.Errorf("unknown connection type")
	}

	return models.ToAppMethod(method), nil
}

// Connected is the resolver for the connected field.
func (r *appResolver) Connected(ctx context.Context, obj *cqrs.App) (bool, error) {
	return !obj.Error.Valid, nil
}

// FunctionCount is the resolver for the functionCount field.
func (r *appResolver) FunctionCount(ctx context.Context, obj *cqrs.App) (int, error) {
	funcs, err := r.Data.GetFunctionsByAppInternalID(ctx, obj.ID)
	if err != nil {
		return 0, err
	}
	return len(funcs), nil
}

// Autodiscovered is the resolver for the autodiscovered field.
func (r *appResolver) Autodiscovered(ctx context.Context, obj *cqrs.App) (bool, error) {
	urls := discovery.URLs()
	_, ok := urls[obj.Url]
	return ok, nil
}

// App is the resolver for the app field.
func (r *connectV1WorkerConnectionResolver) App(ctx context.Context, obj *models.ConnectV1WorkerConnection) (*cqrs.App, error) {
	if obj.AppID == nil {
		return nil, nil
	}

	return r.Data.GetAppByID(ctx, *obj.AppID)
}

// TotalCount is the resolver for the totalCount field.
func (r *connectV1WorkerConnectionsConnectionResolver) TotalCount(ctx context.Context, obj *models.WorkerConnectionsConnection) (int, error) {
	opts := toWorkerConnectionsQueryOpt(0, obj.After, obj.OrderBy, obj.Filter)
	count, err := r.Data.GetWorkerConnectionsCount(ctx, opts)
	if err != nil {
		return 0, fmt.Errorf("error retrieving count for worker connections: %w", err)
	}

	return count, nil
}

// Status is the resolver for the status field.
func (r *eventResolver) Status(ctx context.Context, obj *models.Event) (*models.EventStatus, error) {
	runs, err := r.Data.GetEventRuns(ctx, obj.ID, consts.DevServerAccountID, consts.DevServerEnvID)
	if err != nil {
		return nil, err
	}

	status := models.EventStatusNoFunctions

	if len(runs) == 0 {
		return &status, nil
	}

	status = models.EventStatusCompleted
	var failedRuns int
	var isRunning bool

	for _, s := range runs {
		if s.Status == enums.RunStatusFailed {
			failedRuns++
			continue
		}

		if s.Status == enums.RunStatusRunning {
			isRunning = true
			continue
		}
	}

	if failedRuns > 0 {
		if failedRuns == len(runs) {
			status = models.EventStatusFailed
		} else {
			status = models.EventStatusPartiallyFailed
		}
	} else if isRunning {
		status = models.EventStatusRunning
	}

	return &status, nil
}

// PendingRuns is the resolver for the pendingRuns field.
func (r *eventResolver) PendingRuns(ctx context.Context, obj *models.Event) (*int, error) {
	runs, err := r.Data.GetEventRuns(ctx, obj.ID, consts.DevServerAccountID, consts.DevServerEnvID)
	if err != nil {
		return nil, err
	}

	var pending int
	for _, r := range runs {
		if r.Status == enums.RunStatusRunning {
			pending++
		}
	}

	return &pending, nil
}

// TotalRuns is the resolver for the totalRuns field.
func (r *eventResolver) TotalRuns(ctx context.Context, obj *models.Event) (*int, error) {
	// XXX: This is implemented during a broad refactor;  we should totally implement a query
	// that returns JUST the count for this, so that we don't read and discard data.   I apologize.
	runs, err := r.Data.GetEventRuns(ctx, obj.ID, consts.DevServerAccountID, consts.DevServerEnvID)
	if err != nil {
		return nil, err
	}

	total := len(runs)
	return &total, nil
}

// Raw is the resolver for the raw field.
func (r *eventResolver) Raw(ctx context.Context, obj *models.Event) (*string, error) {
	evt, err := r.Data.GetEventByInternalID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	// Marshall the entire event to JSON and return that string.
	byt, err := json.Marshal(evt.Event())
	if err != nil {
		return nil, err
	}

	jsonStr := string(byt)

	return &jsonStr, nil
}

// TODO Duplicate code. Move to field-level resolvers and add dataloaders.
func (r *eventResolver) FunctionRuns(ctx context.Context, obj *models.Event) ([]*models.FunctionRun, error) {
	runs, err := r.Data.GetFunctionRunsFromEvents(ctx, consts.DevServerAccountID, consts.DevServerEnvID, []ulid.ULID{obj.ID})
	if err != nil {
		return nil, err
	}

	var out []*models.FunctionRun

	for _, run := range runs {
		outRun := models.MakeFunctionRun(run)
		out = append(out, outRun)
	}

	return out, nil
}

// Raw is the resolver for the raw field.
func (r *eventV2Resolver) Raw(ctx context.Context, obj *models.EventV2) (string, error) {
	targetLoader := loader.FromCtx(ctx).EventLoader

	event, err := loader.LoadOneWithString[cqrs.Event](
		ctx,
		targetLoader,
		obj.ID.String(),
	)
	if err != nil {
		return "", err
	}

	raw, err := marshalRaw(event)
	if err != nil {
		return "", err
	}

	return raw, nil
}

// Runs is the resolver for the runs field.
func (r *eventV2Resolver) Runs(ctx context.Context, obj *models.EventV2) ([]*models.FunctionRunV2, error) {
	// convert cqrs TraceRun to FunctionRunV2

	// This is an N+1, currently also an N+1 on cloud in the form of multiple calls to the metrics service
	// we cannot currently use a data loader due to current db schema and https://github.com/sqlc-dev/sqlc/issues/1830
	traceRuns, err := r.Data.GetTraceRunsByTriggerID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	functionRuns := make([]*models.FunctionRunV2, 0, len(traceRuns))
	for _, r := range traceRuns {
		// TODO dedupe cqrs.TraceRun to models.FunctionRunV2 transformation
		var (
			started   *time.Time
			ended     *time.Time
			sourceID  *string
			output    *string
			batchTime *time.Time
		)

		if r.StartedAt.UnixMilli() > 0 {
			started = &r.StartedAt
		}
		if r.EndedAt.UnixMilli() > 0 {
			ended = &r.EndedAt
		}
		if len(r.SourceID) > 0 {
			sourceID = &r.SourceID
		}
		if len(r.Output) > 0 {
			s := string(r.Output)
			output = &s
		}
		runID := ulid.MustParse(r.RunID)
		status, err := models.ToFunctionRunStatus(r.Status)
		if err != nil {
			continue
		}

		functionRuns = append(functionRuns, &models.FunctionRunV2{
			ID:             runID,
			AppID:          r.AppID,
			FunctionID:     r.FunctionID,
			TraceID:        r.TraceID,
			QueuedAt:       r.QueuedAt,
			StartedAt:      started,
			EndedAt:        ended,
			SourceID:       sourceID,
			Status:         status,
			Output:         output,
			IsBatch:        r.IsBatch,
			BatchCreatedAt: batchTime,
			CronSchedule:   r.CronSchedule,
			HasAi:          r.HasAI,
		})
	}
	return functionRuns, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *eventsConnectionResolver) TotalCount(ctx context.Context, obj *models.EventsConnection) (int, error) {
	filter := graphql.GetFieldContext(ctx).Parent.Args["filter"].(models.EventsFilter)

	opts := cqrs.WorkspaceEventsOpts{
		Limit:                 cqrs.MaxEvents, // pass in dummy value to pass validation, but won't be used in actual count query
		Names:                 filter.EventNames,
		IncludeInternalEvents: filter.IncludeInternalEvents,
		Oldest:                filter.From,
	}

	// this relies on the frontend not requesting TotalCount except on loading the first page
	opts.Newest = time.Now()
	if filter.Until != nil {
		opts.Newest = *filter.Until
	}

	totalCount, err := r.Data.GetEventsCount(ctx, consts.DevServerAccountID, consts.DevServerEnvID, opts)

	if err != nil {
		return 0, err
	}
	return int(totalCount), nil
}

// FailureHandler is the resolver for the failureHandler field.
func (r *functionResolver) FailureHandler(ctx context.Context, obj *models.Function) (*models.Function, error) {
	slug := inngest.GetFailureHandlerSlug(obj.Slug)

	failureFn, err := r.Data.GetFunctionByExternalID(ctx, consts.DevServerEnvID, "local", slug)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, err
		}
	}

	return models.MakeFunction(failureFn)
}

// App is the resolver for the app field.
func (r *functionResolver) App(ctx context.Context, obj *models.Function) (*cqrs.App, error) {
	appID := uuid.MustParse(obj.AppID)
	return r.Data.GetAppByID(ctx, appID)
}

// Function is the resolver for the function field.
func (r *functionRunResolver) Function(ctx context.Context, obj *models.FunctionRun) (*models.Function, error) {
	fn, err := r.Data.GetFunctionByInternalUUID(ctx, uuid.MustParse(obj.FunctionID))
	if err != nil {
		return nil, err
	}
	return models.MakeFunction(fn)
}

// Event is the resolver for the event field.
func (r *functionRunResolver) Event(ctx context.Context, obj *models.FunctionRun) (*models.Event, error) {
	eventID, err := ulid.Parse(obj.EventID)
	if err != nil {
		return nil, err
	}

	evt, err := r.Data.GetEventByInternalID(ctx, eventID)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	payload, err := json.Marshal(evt.EventData)
	if err != nil {
		return nil, err
	}

	return &models.Event{
		CreatedAt: &evt.ReceivedAt,
		ID:        evt.InternalID(),
		Name:      &evt.EventName,
		Payload:   util.StrPtr(string(payload)),
	}, nil
}

// Events is the resolver for the events field.
func (r *functionRunResolver) Events(ctx context.Context, obj *models.FunctionRun) ([]*models.Event, error) {
	empty := []*models.Event{}
	runID := ulid.MustParse(obj.ID)

	batch, err := r.Data.GetEventBatchByRunID(ctx, runID)
	if err != nil {
		// if an error occur, it likely means there are no batches for this runID
		// attempt to just return a single event, that's similar to the Event resolver
		evt, err := r.Event(ctx, obj)
		if err != nil {
			return empty, nil
		}

		// Will be nil if the run was not triggered by an event (i.e. a cron)
		if evt == nil {
			return empty, nil
		}

		return []*models.Event{evt}, nil
	}

	// retrieve events by IDs
	evts, err := r.Data.GetEventsByInternalIDs(ctx, batch.EventIDs())
	if err != nil {
		return empty, err
	}

	result := make([]*models.Event, len(evts))
	for i, e := range evts {
		payload, err := json.Marshal(e.EventData)
		if err != nil {
			return empty, err
		}

		result[i] = &models.Event{
			ID:        e.InternalID(),
			Name:      &e.EventName,
			CreatedAt: &e.ReceivedAt,
			Payload:   util.StrPtr(string(payload)),
		}
	}

	return result, nil
}

// BatchCreatedAt is the resolver for the batchCreatedAt field.
func (r *functionRunResolver) BatchCreatedAt(ctx context.Context, obj *models.FunctionRun) (*time.Time, error) {
	batch, err := r.Data.GetEventBatchByRunID(ctx, ulid.MustParse(obj.ID))
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	out := ulid.Time(batch.ID.Time())
	return &out, nil
}

// WaitingFor is the resolver for the waitingFor field.
func (r *functionRunResolver) WaitingFor(ctx context.Context, obj *models.FunctionRun) (*models.StepEventWait, error) {
	return nil, nil
}

// PendingSteps is the resolver for the pendingSteps field.
func (r *functionRunResolver) PendingSteps(ctx context.Context, obj *models.FunctionRun) (*int, error) {
	randomId := uuid.UUID{}

	md, err := r.Runner.StateManager().Metadata(ctx, randomId, ulid.MustParse(obj.ID))
	if err != nil {
		zero := 0
		if errors.Is(err, statev1.ErrRunNotFound) {
			return &zero, nil
		}
		return nil, fmt.Errorf("Run ID not found: %w", err)
	}
	pending, _ := r.Queue.OutstandingJobCount(
		ctx,
		md.Identifier.WorkspaceID,
		md.Identifier.WorkflowID,
		md.Identifier.RunID,
	)
	return &pending, nil
}

// History is the resolver for the history field.
func (r *functionRunResolver) History(ctx context.Context, obj *models.FunctionRun) ([]*history_reader.RunHistory, error) {
	runID, err := ulid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid run ID: %w", err)
	}

	return r.HistoryReader.GetRunHistory(
		ctx,
		runID,
		history_reader.GetRunOpts{
			AccountID: consts.DevServerAccountID,
		},
	)
}

// HistoryItemOutput is the resolver for the historyItemOutput field.
func (r *functionRunResolver) HistoryItemOutput(ctx context.Context, obj *models.FunctionRun, id ulid.ULID) (*string, error) {
	runID, err := ulid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid run ID: %w", err)
	}

	return r.HistoryReader.GetRunHistoryItemOutput(
		ctx,
		id,
		history_reader.GetHistoryOutputOpts{
			AccountID: consts.DevServerAccountID,
			RunID:     runID,

			// TODO: Where should we get this?
			WorkflowID: uuid.New(),

			WorkspaceID: consts.DevServerEnvID,
		},
	)
}

// App is the resolver for the app field.
func (r *functionRunV2Resolver) App(ctx context.Context, obj *models.FunctionRunV2) (*cqrs.App, error) {
	return r.Data.GetAppByID(ctx, obj.AppID)
}

// Function is the resolver for the function field.
func (r *functionRunV2Resolver) Function(ctx context.Context, obj *models.FunctionRunV2) (*models.Function, error) {
	fun, err := r.Data.GetFunctionByInternalUUID(ctx, obj.FunctionID)
	if err != nil {
		return nil, fmt.Errorf("error retrieving function: %w", err)
	}

	return models.MakeFunction(fun)
}

// Trace is the resolver for the trace field.
func (r *functionRunV2Resolver) Trace(ctx context.Context, obj *models.FunctionRunV2, preview *bool) (*models.RunTraceSpan, error) {
	targetLoader := loader.FromCtx(ctx).LegacyRunTraceLoader
	if preview != nil && *preview {
		targetLoader = loader.FromCtx(ctx).RunTraceLoader
	}

	return loader.LoadOne[models.RunTraceSpan](
		ctx,
		targetLoader,
		&loader.TraceRequestKey{
			TraceRunIdentifier: &cqrs.TraceRunIdentifier{
				AppID:      obj.AppID,
				FunctionID: obj.FunctionID,
				RunID:      obj.ID,
				TraceID:    obj.TraceID,
			},
		},
	)
}

// TotalCount is the resolver for the totalCount field.
func (r *runsV2ConnectionResolver) TotalCount(ctx context.Context, obj *models.RunsV2Connection, preview *bool) (int, error) {
	opts := toRunsQueryOpt(0, obj.After, obj.OrderBy, obj.Filter, preview)
	count, err := r.Data.GetTraceRunsCount(ctx, opts)
	if err != nil {
		return 0, fmt.Errorf("error retrieving count for runs: %w", err)
	}

	return count, nil
}

// InBatch is the resolver for the inBatch field.
func (r *streamItemResolver) InBatch(ctx context.Context, obj *models.StreamItem) (bool, error) {
	eventID, err := ulid.Parse(obj.ID)
	if err != nil {
		return false, err
	}

	batches, err := r.Data.GetEventBatchesByEventID(ctx, eventID)
	if err != nil {
		return false, err
	}

	return len(batches) > 0, nil
}

// App returns generated.AppResolver implementation.
func (r *Resolver) App() generated.AppResolver { return &appResolver{r} }

// ConnectV1WorkerConnection returns generated.ConnectV1WorkerConnectionResolver implementation.
func (r *Resolver) ConnectV1WorkerConnection() generated.ConnectV1WorkerConnectionResolver {
	return &connectV1WorkerConnectionResolver{r}
}

// ConnectV1WorkerConnectionsConnection returns generated.ConnectV1WorkerConnectionsConnectionResolver implementation.
func (r *Resolver) ConnectV1WorkerConnectionsConnection() generated.ConnectV1WorkerConnectionsConnectionResolver {
	return &connectV1WorkerConnectionsConnectionResolver{r}
}

// Event returns generated.EventResolver implementation.
func (r *Resolver) Event() generated.EventResolver { return &eventResolver{r} }

// EventV2 returns generated.EventV2Resolver implementation.
func (r *Resolver) EventV2() generated.EventV2Resolver { return &eventV2Resolver{r} }

// EventsConnection returns generated.EventsConnectionResolver implementation.
func (r *Resolver) EventsConnection() generated.EventsConnectionResolver {
	return &eventsConnectionResolver{r}
}

// Function returns generated.FunctionResolver implementation.
func (r *Resolver) Function() generated.FunctionResolver { return &functionResolver{r} }

// FunctionRun returns generated.FunctionRunResolver implementation.
func (r *Resolver) FunctionRun() generated.FunctionRunResolver { return &functionRunResolver{r} }

// FunctionRunV2 returns generated.FunctionRunV2Resolver implementation.
func (r *Resolver) FunctionRunV2() generated.FunctionRunV2Resolver { return &functionRunV2Resolver{r} }

// RunsV2Connection returns generated.RunsV2ConnectionResolver implementation.
func (r *Resolver) RunsV2Connection() generated.RunsV2ConnectionResolver {
	return &runsV2ConnectionResolver{r}
}

// StreamItem returns generated.StreamItemResolver implementation.
func (r *Resolver) StreamItem() generated.StreamItemResolver { return &streamItemResolver{r} }

type appResolver struct{ *Resolver }
type connectV1WorkerConnectionResolver struct{ *Resolver }
type connectV1WorkerConnectionsConnectionResolver struct{ *Resolver }
type eventResolver struct{ *Resolver }
type eventV2Resolver struct{ *Resolver }
type eventsConnectionResolver struct{ *Resolver }
type functionResolver struct{ *Resolver }
type functionRunResolver struct{ *Resolver }
type functionRunV2Resolver struct{ *Resolver }
type runsV2ConnectionResolver struct{ *Resolver }
type streamItemResolver struct{ *Resolver }
