export const statusTitles: Record<string, string> = {
  ABORTED: 'Aborted',
  CANCELED: 'Canceled',
  CANCELLED: 'Canceled',
  COMPLETED: 'Completed',
  FAILED: 'Failed',
  RUNNING: 'Running',
  QUEUED: 'Queued',
  SKIPPED: 'Skipped',
  SKIPPED_PAUSED: 'Skipped',
  PAUSED: 'Paused',
  INACTIVE: 'Inactive',
  ACTIVE: 'Active',
  ARCHIVED: 'Archived',
};
