export const statusTitles: Record<string, string> = {
  CANCELED: 'Canceled',
  CANCELLED: 'Canceled',
  COMPLETED: 'Completed',
  FAILED: 'Failed',
  RUNNING: 'Running',
  QUEUED: 'Queued',
  SKIPPED_PAUSED: 'Skipped',
  PAUSED: 'Paused',
  CONNECTED: 'Inactive',
  DISCONNECTED: 'Failed',
  DISCONNECTING: 'Inactive',
  DRAINING: 'Inactive',
  READY: 'Active',
};
