// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	ulid "github.com/oklog/ulid/v2"
)

type App struct {
	ID          uuid.UUID
	Name        string
	SdkLanguage string
	SdkVersion  string
	Framework   sql.NullString
	Metadata    string
	Status      string
	Error       sql.NullString
	Checksum    string
	CreatedAt   time.Time
	DeletedAt   sql.NullTime
	Url         string
}

type Event struct {
	InternalID ulid.ULID
	EventID    string
	EventName  string
	EventData  string
	EventUser  string
	EventV     sql.NullString
	EventTs    time.Time
}

type Function struct {
	ID        uuid.UUID
	AppID     uuid.UUID
	Name      string
	Slug      string
	Config    string
	CreatedAt time.Time
}

type FunctionFinish struct {
	RunID              ulid.ULID
	Status             string
	Output             string
	CompletedStepCount int64
	CreatedAt          time.Time
}

type FunctionRun struct {
	RunID           ulid.ULID
	RunStartedAt    time.Time
	FunctionID      uuid.UUID
	FunctionVersion int64
	TriggerType     string
	EventID         ulid.ULID
	BatchID         ulid.ULID
	OriginalRunID   ulid.ULID
	Cron            sql.NullString
}

type History struct {
	ID              ulid.ULID
	CreatedAt       time.Time
	RunStartedAt    time.Time
	FunctionID      uuid.UUID
	FunctionVersion int64
	RunID           ulid.ULID
	EventID         ulid.ULID
	BatchID         ulid.ULID
	GroupID         sql.NullString
	IdempotencyKey  string
	Type            string
	Attempt         int64
	LatencyMs       sql.NullInt64
	StepName        sql.NullString
	StepID          sql.NullString
	Url             sql.NullString
	CancelRequest   sql.NullString
	Sleep           sql.NullString
	WaitForEvent    sql.NullString
	WaitResult      sql.NullString
	Result          sql.NullString
}
