name: Shared UI

on:
  push:
    branches: [main]
    paths:
      - "ui/packages/components/**"
  pull_request:
    paths:
      - "ui/packages/components/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: "10.18.2"
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"
      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: ui/packages/components
      - name: Lint
        run: pnpm lint
        working-directory: ui/packages/components
      - name: Test
        run: pnpm test
        working-directory: ui/packages/components
