name: Shared UI

on:
  push:
    branches: [main]
    paths:
      - "ui/packages/components/**"
  pull_request:
    paths:
      - "ui/packages/components/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
        with:
          version: "10.33.2"
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"
      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: ui/packages/components
      - name: Lint
        run: pnpm lint
        working-directory: ui/packages/components
      - name: Test
        run: pnpm test
        working-directory: ui/packages/components
