name: Go

on:
  push:
    branches: [main]
    paths-ignore:
      - "ui/**"
  pull_request:
    paths-ignore:
      - "ui/**"

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: ./go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.2.1
          args: --verbose

  gen:
    name: 'git state after "make gen protobuf"'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: true
      - uses: DeterminateSystems/nix-installer-action@430608d219b9321ec0c98eb6c37245a39aa6756e # main
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - name: 'Check for dirty Git state after running "make gen protobuf"'
        run: |
          make gen protobuf
          git diff
          git diff --name-only --exit-code

  test-linux-race:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        experimentalKeyQueues: [false, true]
        enableConstraintAPI: [false, true]
        database: [sqlite, postgres]
    runs-on: ${{ matrix.os }}
    name: "Test / OS: ${{ matrix.os }}, key-queues: ${{ matrix.experimentalKeyQueues }}, constraint-api: ${{ matrix.enableConstraintAPI }}, db: ${{ matrix.database }}"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: ./go.mod

      - name: Test
        run: |
          go test -v $(find . -iname "*_test.go" | xargs -I {} dirname {} | uniq | grep -v "./tests") -race -count=1 -coverprofile=coverage.txt
        env:
          TEST_MODE: true
          EXPERIMENTAL_KEY_QUEUES_ENABLE: "${{ matrix.experimentalKeyQueues }}"
          ENABLE_CONSTRAINT_API: "${{ matrix.enableConstraintAPI }}"
          TEST_DATABASE: "${{ matrix.database }}"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,kq-${{ matrix.experimentalKeyQueues }},db-${{ matrix.database }}
