name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - "ui/**"
  pull_request:
    paths-ignore:
      - "ui/**"

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    strategy:
      matrix:
        os: [depot-ubuntu-22.04-4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.4
          args: --verbose

  gen:
    name: 'git state after "make gen protobuf"'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicknovitski/nix-develop@v1.2.1
      - name: 'Check for dirty Git state after running "make gen protobuf"'
        run: |
          make gen protobuf
          git diff
          git diff --name-only --exit-code

  test-linux-race:
    strategy:
      fail-fast: false
      matrix:
        os: [depot-ubuntu-22.04-4]
        database: [sqlite, postgres]
    runs-on: ${{ matrix.os }}
    name: "Test / OS: ${{ matrix.os }}, db: ${{ matrix.database }}"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.13.0

      - name: Test
        run: |
          gotestsum --junitfile=junit.xml --format=standard-verbose -- \
            $(find . -iname "*_test.go" | xargs -I {} dirname {} | uniq | grep -v "./tests") \
            -race -count=1 -coverprofile=coverage.txt
        env:
          TEST_MODE: true
          TEST_DATABASE: "${{ matrix.database }}"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,db-${{ matrix.database }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./junit.xml
          flags: unit,db-${{ matrix.database }}
          report_type: test_results
