name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - name: Build UI
        run: make build-ui

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: "1.20"
          dest: build
          prefix: inngest
          pkg: cmd
          targets: linux/arm64,linux/amd64,darwin/arm64,darwin/amd64,windows/amd64
          v: false
          x: false
          race: false
          ldflags: -s -w -X github.com/inngest/inngest/pkg/inngest/version.Version=${{ steps.meta.outputs.tag }} -X github.com/inngest/inngest/pkg/inngest/version.Hash=${{ steps.meta.outputs.sha }}
          buildmode: default
          trimpath: true

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: ./build/*
          retention-days: 5
