name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * 1,5"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 90
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been inactive for 60 days and is now marked as stale."
          close-issue-message: "This issue has been automatically closed due to inactivity for 90 days."
          days-before-pr-stale: -1
          days-before-pr-close: -1
